### ISSUE TITLE
Foreign keys referencing to non-existing tables when baking snapshot

### ISSUE THREAD

**Issue by GuidoHendriks** [cakephp/migrations#100]
When baking a snapshot, foreign keys are added correctly now. But there's a problem when migrating to the snapshot. Tables are added in alphabetical order. So in a lot of cases it'll add a foreign key for a not yet existing table, which leads to database errors:

      SQLSTATE[HY000]: General error: 1005 Can't create table 'foo.bar' (errno: 150)

Example of the way it's created:

```php
$this->table('bar')
    ->addColumn('bar_id', 'integer')
    ->addForeignKey('foo_id', 'foo', 'id')
    ->create();

$table = $this->table('foo')
    ->create();
```

**Comment by HavokInspiration** [comment]
I'll take a look

**Comment by HavokInspiration** [comment]
Pull request up #101
