### ISSUE TITLE
Running migrations from code?

### ISSUE THREAD

**Issue by burzum** [cakephp/migrations#114]
Is there a way to run migrations from within my applications code? The use case is a plugin system that allows me to install / deinstall plugins and to trigger their migrations.

What I would like to do is something like this (Pseudocode!):

```php
$migrations = new Migrations();
try {
    return $migrations->migrate('MyFancyPlugin');
} catch (Exception $e) {
    return false;
}
```

It would be nice if the migration would return a meaningful state. I think this problem was discussed before as well. The underlying migration lib by default was IMHO not properly done because it was built tightly coupled to a shell application. So the result you get back is some console output you would have to parse.

The ideal scenario would be to get a simple boolean back but have the ability to call something like getErrors() in the case of a failure to see the exact problem.

Is this already possible? If yes, it should be documented.

**Comment by burzum** [comment]
Meh just found this https://github.com/cakephp/migrations/pull/97

**Comment by jhli** [comment]
You can also look at how Croogo does some of that and maybe it is already solved on croogo for cake3 @rchavik.

**Comment by rchavik** [comment]
Nope. We haven't gotten there yet on 3.x.
