### ISSUE TITLE
Running all migrations

### ISSUE THREAD

**Issue by bobmulder** [cakephp/migrations#115]
Hey guys,

I have a plugin wich has dependencies, so when you install that plugin, you have to run multiple migrations (for every plugin once).
Is there a way to create a command wich will run every migration, so of the app, and all plugins?

Greetz

**Comment by lorenzo** [comment]
No, there is no command for that

**Comment by josegonzalez** [comment]
You can get a list of all loaded plugins and then run the migrations manually for each plugin as of [1.2](https://github.com/cakephp/migrations/releases/tag/1.2).

**Comment by bobmulder** [comment]
@josegonzalez How should I run all migrations with a list of all plugins?

Tried this:
```
        $this->dispatchShell('migrations migrate -p CakeAdmin');
        $this->dispatchShell('migrations migrate -p Notifier');
        $this->dispatchShell('migrations migrate -p Settings');
```
But the command will stop after the first migration...

**Comment by lorenzo** [comment]
I would just do a basic shell script or make file, there is no actual need to run this from php

**Comment by bobmulder** [comment]
@josegonzalez I guess this method (https://github.com/cakephp/migrations/blob/master/src/Migrations.php#L88-L102) will run all available (including all plugin) migrations?

**Comment by HavokInspiration** [comment]
This method will run all available migrations **based on the params you pass**.
So if you want to run all migrations for all your plugin, you still need to do what @josegonzalez suggested : get a list of all loaded plugins and run the migrations. Something like this :

```php
$plugins = Plugin::loaded();
foreach ($plugins as $plugin) {
	$migrations->migrate(['plugin' => $plugin]);
}
```

**Comment by bobmulder** [comment]
Great, thanks for the example @HavokInspiration :+1:

**Comment by HavokInspiration** [comment]
You can also take a look at the [CakePHP Cookbook](http://book.cakephp.org/3.0/en/migrations.html#running-migrations-in-a-non-shell-environment) if you need more infos on how to run migrations in a non-shell environment.
If some informations seem unclear, please tell us.

**Comment by bobmulder** [comment]
Ah I didn't know about that info. I thought the migration-doc was on this repo. Thanks for noticing me! :)
