### ISSUE TITLE
Missing date option from Phinx v. 0.4.5

### ISSUE THREAD

**Issue by xicrow** [cakephp/migrations#117]
Since an update today to Phinx v. 0.4.5, Phinx has added the `date` option to migrations.

Phinx\Console\Command\Migrate::configure():
`->addOption('--date', '-d', InputOption::VALUE_REQUIRED, 'The date to migrate to')`

The update makes migrations throw the `InvalidArgumentException` since the `date` option is not defined in the CakePHP wrapper.

With the line below added to the CakePHP wrapper, everythings working again.

Migrations\Command\Migrate::configure():
`->addOption('--date', '-d', InputArgument::OPTIONAL, 'The date to migrate to')`

**Comment by HavokInspiration** [comment]
I'll take care of this

**Comment by HavokInspiration** [comment]
Pull request up : #118

**Comment by rafwell** [comment]
Same problem here.
