### ISSUE TITLE
Possible error in Usage readme instructions

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/migrations#12]
At **Usage** section, we have instruction to execute in console:

`bin/cake migrations`

But, at least for me (in different environments), the correct command is:

`bin/cake Migrations.migrations`

When I run the first one, the output is: 

> Exception: Shell class for "Migrations" could not be found. in [/vagrant/my_project/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 254]

**Comment by bravo-kernel** [comment]
Maybe this will help fellow idiots.... the exact same error is produced when running migrations with ``debug = false`` :cry:

**Comment by jhli** [comment]
@CauanCabral is it in the docs? Could you add it, if not?

**Comment by CauanCabral** [comment]
@jhli yes, it's here: https://github.com/cakephp/migrations#configuration
