### ISSUE TITLE
CakeAdapter throws InvalidArgumentException when creating database

### ISSUE THREAD

**Issue by sdustinh** [cakephp/migrations#126]
I wrote a migration that checks to create the database itself if it does not already exist. The problem is the `CakeAdapter` is constructed calling the [`getConnection()`](https://github.com/cakephp/migrations/blob/master/src/CakeAdapter.php#L54) method which throws the [`InvalidArgumentException`](https://github.com/robmorgan/phinx/blob/0.4.x-dev/src%2FPhinx%2FDb%2FAdapter%2FMysqlAdapter.php#L113-L116) in Phinx. This makes it impossible to create a database using the migrations plugin.

**Comment by HavokInspiration** [comment]
Can you provide the migration file please ?

**Comment by sdustinh** [comment]
Of course, my bad. I should have included it to begin with. This is roughly what it looks like...

```php
class CreateDatabase extends AbstractMigration
{
    public function down()
    {
        $adapter = $this->getAdapter();
        
        if ($this->hasDatabase('products')) {
            $adapter->dropDatabase('products');
        }
    }
    
    public function up()
    {
        $adapter = $this->getAdapter();
        
        if (!$adapter->hasDatabase('products')) {
            $options = ['collation' => 'utf8_unicode_ci'];
            $adapter->createDatabase('products', $options);
        }
    }
}
```

**Comment by HavokInspiration** [comment]
I can't reproduce the issue.
Could it be a problem with your DB credentials ?
What is the message the Exception is returning ?

**Comment by sdustinh** [comment]
Really? That's strange.

My other migrations in the same plugin work just fine. It's only the create database calls. Here is all of the relevant info for you to check out: https://gist.github.com/sdustinh/78a9e346cae182929f23

**Comment by HavokInspiration** [comment]
Thanks for the gists, that will help me figure everything out.

**Comment by HavokInspiration** [comment]
Why is there a difference in the migration provided in gist (https://gist.github.com/sdustinh/78a9e346cae182929f23#file-20150916155106_create_database-php) and the one you pasted here https://github.com/cakephp/migrations/issues/126#issuecomment-140815998 ?
Which one do you actually use ?

**Comment by sdustinh** [comment]
The one in the gist has been stripped down to show only the relevant parts that directly contribute to the exception being thrown. The one in the initial comment is my first draft when I came across the bug. You can see that the migration extends `App\AbstractMigration' in the gist. Just to eliminate the curiosity that something there might be causing it here is the complete source on that...

```php
<?php
namespace App;

use Migrations\AbstractMigration as CakeAbstractMigration;

/**
 * Configures migration classes for the application.
 */
class AbstractMigration extends CakeAbstractMigration
{
    /**
     * Specifies the table configuration.
     *
     * Forces the collation and database engine to be standard
     * application-wide.
     *
     * @param  string $tableName Table name.
     * @param  array $options Options for the table.
     * @return \Phinx\Db\Table
     */
    public function table($tableName, $options = [])
    {
        $options += [
            'collation' => 'utf8_unicode_ci',
            'engine' => 'InnoDB'
        ];
        return parent::table($tableName, $options);
    }
}
```

Once this is fixed the end result will likely be something similar to the one in the comment (with the checks to see if the database exists) just to prevent errors.

The database config is inconsequential for this plugin. The only difference between `products` and `default` is the database name. I get the same error when I run similar migrations on the default connection.

The bug is the difference in these two files:
- [Phinx\Db\Adapter\PdoAdapter](https://github.com/robmorgan/phinx/blob/master/src%2FPhinx%2FDb%2FAdapter%2FPdoAdapter.php#L75-L81)
- [Cake\Migrations\CakeAdapter](https://github.com/cakephp/migrations/blob/master/src/CakeAdapter.php#L50-L56)

Because the `CakeAdapter` initializes the connection in the constructor it is impossible to create a database that does not exist with the connection that it is using. It's right to throw the exception. The bug is just that the connection initialization should be deferred so a `createDatabase()` call can be made if necessary.

**Comment by HavokInspiration** [comment]
Thanks for the extra context.
What is bothering me is that despite all your informations and the fact that I'm trying to get as closed as I can get from your context, I can't reproduce the bug.

I have a database config that is connecting to an existing database (called ``cakephpapp``) :

```php
'default' => [
    'className' => 'Cake\Database\Connection',
    'driver' => 'Cake\Database\Driver\Mysql',
    'persistent' => false,
    'host' => 'localhost',
    'username' => 'cakephpapp',
    'password' => 'cakephpapp',
    'database' => 'cakephpapp',
    'encoding' => 'utf8',
    'timezone' => 'UTC',
    'cacheMetadata' => true
]
```
The ``products`` database does not exist.
I created the ``App\AbstractMigrations`` class and used as the parent class from the migrations from your comment.

```php
<?php
use App\AbstractMigration;

class CreateDatabase extends AbstractMigration
{
    public function down()
    {
        $adapter = $this->getAdapter();

        if ($adapter->hasDatabase('products')) {
            $adapter->dropDatabase('products');
        }
    }

    public function up()
    {
        $adapter = $this->getAdapter();

        if (!$adapter->hasDatabase('products')) {
            $options = ['collation' => 'utf8_unicode_ci'];
            $adapter->createDatabase('products', $options);
        }
    }
}
```

And it works. It creates the database ``products``.
I'll do some more tests to see if there is something that I'm missing.

**Comment by HavokInspiration** [comment]
Thanks for the extra context.
What is bothering me is that despite all your informations and the fact that I'm trying to get as closed as I can get from your context, I can't reproduce the bug.

I have a database config that is connecting to **an existing database** (called ``cakephpapp``) :

```php
'default' => [
    'className' => 'Cake\Database\Connection',
    'driver' => 'Cake\Database\Driver\Mysql',
    'persistent' => false,
    'host' => 'localhost',
    'username' => 'cakephpapp',
    'password' => 'cakephpapp',
    'database' => 'cakephpapp',
    'encoding' => 'utf8',
    'timezone' => 'UTC',
    'cacheMetadata' => true
]
```
The ``products`` database does not exist.
I created the ``App\AbstractMigrations`` class and used as the parent class from the migrations from your comment.

```php
<?php
use App\AbstractMigration;

class CreateDatabase extends AbstractMigration
{
    public function down()
    {
        $adapter = $this->getAdapter();

        if ($adapter->hasDatabase('products')) {
            $adapter->dropDatabase('products');
        }
    }

    public function up()
    {
        $adapter = $this->getAdapter();

        if (!$adapter->hasDatabase('products')) {
            $options = ['collation' => 'utf8_unicode_ci'];
            $adapter->createDatabase('products', $options);
        }
    }
}
```

And it works. It creates the database ``products``.
I'll do some more tests to see if there is something that I'm missing.

The only way I can reproduce the bug is if I connect to the database ``products``, which is logical since you can not connect to a database that does not exists with PDO.

**Comment by sdustinh** [comment]
Ah, that's our problem right there. I'm creating a database that does not exist at all yet.

What I'm trying to do is check out the application from git, install the dependencies with composer and initialize the database with migrations. The connection information is in environment variables. If the database it is trying to create already exists I use `mark_migrated` to just skip it.

I'm trying to circumvent having to create any of the databases manually since I have an application that has 4 databases - 3 of those databases are defined by plugins.

**Comment by sdustinh** [comment]
Oh actually... it still fails to create a database even with my `default` database able to connect. It's because the `products` connection defines `'database' => 'products'`. So technically I could run: `bin/cake migrations migrate -p Products -t <create db version>` which would create the database and then I'd have to run `bin/cake migrations migrate -c products -p Products` to migrate the rest.

**Comment by HavokInspiration** [comment]
This should work yes.

**Comment by sdustinh** [comment]
Ah, I guess I should move my database creation stuff to the main application. There is still the problem of creating on an uninitialized database for the `default` connection.

Would you be open to a pull request that lazy loads the connection so this would be possible? I haven't looked into how difficult this would be but I'd be happy to take a run at it if you think it's something worth having.

**Comment by HavokInspiration** [comment]
What you are trying to do should be done outside of the migrations system. When the MysqlAdapter (or any Adapter) establishes (or tries to establish) a connection to the database, one of the first thing it does is checking if the ``phinxlog`` table exists : if it does not, it tries to create it (even before checking if there are migrations to migrate or rollback). But in order to create it, it needs a database. Which is what is blocking you here.

You should create the database in the installation script that is checking out your repo and calling the ``bin/cake migrations migrate`` call.

**Comment by sdustinh** [comment]
After playing around with this hiccup yesterday I agree with you. This is a non-issue since the only issue here is that I have to create the initial database.

Thanks for your help and sorry for wasting your time with this! I appreciate it.

**Comment by HavokInspiration** [comment]
Don't worry. I'm glad I could be of help.
