### ISSUE TITLE
Feature Request: Specify field length on CLI

### ISSUE THREAD

**Issue by JoeThielen** [cakephp/migrations#128]
I apologize if this has been asked before, I've done a search here and did not find it.  Would it be possible to add the ability to specify field length via the CLI?

field:fieldType:indexType:indexName:fieldLength

Or even add an autosense from the fieldType... when "string128" is used over "string", use the 128 as the length?  

The reason I ask is that this would help in terms of writing documentation, as well as for automation via scripting.  Being able to specify a simple one-line copy and paste CLI example is easier than multi-line migration file or direct SQL.  I know is pedantic, but the existing CLI comes so very close already and is such a great feature, thanks to all involved.  As a newbie to CakePHP I'm taking in all the documentation and trying to give back where I can in suggestions here.

**Comment by markstory** [comment]
> I apologize if this has been asked before, I've done a search here and did not find it. Would it be possible to add the ability to specify field length via the CLI?

As soon as someone implements it :smile:. Without any delimiters, finding the length and the column type could get a bit tricky. Perhaps something like `string[128]` or `string(128)` could work?

**Comment by JoeThielen** [comment]
I'd personally be fine with whatever method you all come up with, as long as it can be implemented from the CLI :smile: .  It's nothing that needs immediate reaction, but maybe something that could be looked into for the future.

**Comment by lorenzo** [comment]
It is possible to specify the length:

```
name:string:40
```

**Comment by JoeThielen** [comment]
:smile:  I tried this and it didn't work.  Thanks for the glimmer of hope though, ha.

**Comment by HavokInspiration** [comment]
That's a good idea.

> Perhaps something like string[128] or string(128) could work?

I like the ``string(128)`` writing. Adding another ``:something`` writing would indeed get tricky real quick.
Plus, it's closer to the real writing.

**Comment by HavokInspiration** [comment]
I started working on this.
FYI, I went with ``string[128]`` because using parenthesis causes the shell call to fail.

**Comment by markstory** [comment]
@HavokInspiration Sounds good.

**Comment by JoeThielen** [comment]
Thanks so much!  I was figuring some delimiters would cause issues on the CLI.

**Comment by josegonzalez** [comment]
@JoeThielen I stole the idea from Rails and the company I previously made the feature for went out of business so... Open Source!

**Comment by HavokInspiration** [comment]
Done in #140
