### ISSUE TITLE
RFC: mark_migrated "up to" a certain version number

### ISSUE THREAD

**Issue by ravage84** [cakephp/migrations#129]
After seeing https://github.com/cakephp/migrations/pull/125 being merged, it reminded me on [my feature request](https://github.com/CakeDC/migrations/issues/223) for [CakeDC/migrations](https://github.com/CakeDC/migrations/).

So in additon of having the current two mark_migrated commands:

````
# The following will mark targeted migration as marked without actually running it.
# The expected argument is the migration version number
bin/cake migrations mark_migrated 20150417223600

# Since Migrations 1.3.1, a new `all` special value for the version argumentwas added.
# The following will mark all migrations found as migrated.
bin/cake migrations mark_migrated all
````

I propose one more, to allow to mark all versions up to a given version number as migrated without running them.

**Comment by HavokInspiration** [comment]
I can see some value to this.
We could add a flag that, when present, instead of just marking the target as migrated will mark all of them up to the target.
Something like :

```
bin/cake migrations mark_migrated --up-to 20150417223600
```

Would you expect the given version number to be migrated as well or stop to the one just before it ?

**Comment by ravage84** [comment]
@HavokInspiration with "up to" I would assume it would include the given version number.

**Comment by dakota** [comment]
@HavokInspiration `--target` (or `-t`) to match the `migrate` and `rollback` commands. Sounds like a good idea to me. :+1:

**Comment by pedrofs** [comment]
Sorry the mess! :)

**Comment by HavokInspiration** [comment]
Closing as #137 is open.
