### ISSUE TITLE
RFC: Migration Generation via Schema Comparison

### ISSUE THREAD

**Issue by JD-Robbs** [cakephp/migrations#131]
CakePHP 2.5 (edit: read "2.x") and its migration plugin had the nifty feature of automatically generating "incremental" migrations based on schema comparisons - saving one from manually having write-out the migrations.

For that purpose, CakePHP used this nifty method (after getting confirmation via the CLI): https://github.com/cakephp/cakephp/blob/2.5/lib/Cake/Model/CakeSchema.php#L451

I wonder if something similar was/is planned for the new Migrations plugin?

**Comment by HavokInspiration** [comment]
Seems like a duplicate of #104

**Comment by JD-Robbs** [comment]
Whoopsie - I missed that. My apologies. :smiley:
