### ISSUE TITLE
Namespace for migration's files

### ISSUE THREAD

**Issue by cake17** [cakephp/migrations#139]
Which namespace should we use for migration's files that resides in `config/Migrations` ?

This is to solved the phpcs error I get each time I run [cakephp-codesniffer](https://github.com/cakephp/cakephp-codesniffer):

    Each class must be in a namespace of at least one level
    (a top-level vendor name)

**Comment by HavokInspiration** [comment]
That is a good question.
We need to have a namespace that will respect PSR and we do not define a root namespace for the ``config`` dir.

**Comment by HavokInspiration** [comment]
Can we have a dummy namespace ? Something like ``Config\{MIGRATION_DIR}`` ? 
Does that break anything with PSR ?

I can try and see if that breaks anything code-wise.

**Comment by cake17** [comment]
@HavokInspiration did you try with a dummy namespace ?

While reading PSR2, having a namespace doesn't seem to be an obligation:

    **When present**, there MUST be one blank line after the namespace declaration

So maybe I'll only test in `/src` and `/tests` with cakephp/codesniffer

**Comment by HavokInspiration** [comment]
I did not try it yet.

**Comment by HavokInspiration** [comment]
I did not try it yet.
Excluding ``config`` from testing can be a solution but it is worth checking it out.

**Comment by HavokInspiration** [comment]
@cake17 Using a dummy namespace raises an exception.

**Comment by jadb** [comment]
What's the benefit of having a namespace here?

**Comment by HavokInspiration** [comment]
@jadb I think @cake17 asked the question because he was sniffing the ``config`` directory, where migrations are stored and it was raising an error asking for a namespace in Migrations class files.
In my opinion, the best course of action if the ``config`` is sniffed would be to exclude the folder containing the migrations.

**Comment by cake17** [comment]
@HavokInspiration @jadb exactly ! I was wondering if all classes had to be under a namespace to follow psr-2. I don't sniff `config` anymore. Maybe we can close this

**Comment by bravo-kernel** [comment]
Too bad this is closed. Now that my migration files are becoming more complex (and larger) bad CS is starting to slip in and I would really lke to run the sniffer against them.

Any chance of this ever becoming viable?

**Comment by HavokInspiration** [comment]
We could potentially add a new namespace in the app skeleton pointing to the config/Migrations dir.
If we go down that road, we should also have ``bake`` add a new namespace to the composer.json file when a plugin is baked.

And make sure migrations file can be easily loaded with a new namespace.

This will need more digging for sure if this is becoming a most wanted feature.

There's also https://github.com/robmorgan/phinx/issues/168 to keep an eye on.
