### ISSUE TITLE
Mirgations vs. Bake Generate Different Migration Scaffolds

### ISSUE THREAD

**Issue by JD-Robbs** [cakephp/migrations#143]
Not a biggie, but I realised that depending on whether you use `bin/cake bake migration TestMigration` or `bin/cake migrations create TestMigration`, you get different resulting files.

**`bin/cake bake migration TestMigration`:**

```
use Migrations\AbstractMigration;

class TestMigration extends AbstractMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-change-method
     * @return void
     */
    public function change()
    {
    }
}
```

**`bin/cake migrations create TestMigration`:**

```
<?php

use Phinx\Migration\AbstractMigration;

class TesterMigration extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change()
    {

    }
}
```

Functionally, they're both ~~different~~ **equivalent** (edit: Freudian slip), of course. 

I merely wonder if it'd make sense for the latter to also extend the migration class's subclass (`Migrations/AbstractMigration`) rather than extending Phinx's directly - just in the event this ever gets a new adapter some time down the line.

**Comment by HavokInspiration** [comment]
I'm wondering altogether if we should remove the ``create`` command from the wrapper, given than the bake command does quite a lot of things.
I've personally never had a need for the ``create`` command.

I'm open to suggestions on this one.

**Comment by lorenzo** [comment]
We could make the create command call bake instead...

**Comment by dereuromark** [comment]
We should probably only do that if bake plugin exists and is loaded.

**Comment by HavokInspiration** [comment]
@lorenzo That could be a solution. But I'm wondering if that's possible since the ``create`` command does not take the same arguments / options as bake.
This is going to need some investigations.

**Comment by josegonzalez** [comment]
Given the flexibility that the `bake` command gives us - generation of migrations via cli etc. - I think doing as @lorenzo says is probably best.

**Comment by HavokInspiration** [comment]
PR #299 opened.
