### ISSUE TITLE
migration class not found

### ISSUE THREAD

**Issue by YassineKhadouch** [cakephp/migrations#146]
i have a problem executing this: bin/cake bake migration CreateCategories parent_id:integer lft:integer[10] rght:integer[10] name:string[100] description:string created modified

Error:
Exception: Shell class for "Migration" could not be found. in [/Applications/MAMP/htdocs/blog/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 290]

this works fine: ./bin/cake migrations create CreateArticles

**Comment by HavokInspiration** [comment]
What version of the plugin are you using ?
What version of CakePHP ?

**Comment by YassineKhadouch** [comment]
CakePHP v3.1.3
Migrations plugin v0.4.1

**Comment by HavokInspiration** [comment]
By plugin, I meant the version of the cakephp/migrations plugin (I suspect you gave me phinx version).
You can use ``composer show -i`` to get all package installed along with the version number.

**Comment by YassineKhadouch** [comment]
Ok here we go: cakephp/migrations v1.4

**Comment by HavokInspiration** [comment]
Can you bake anything else ? Like a ``controller`` or a ``model`` (``bin/cake bake controller`` or ``bin/cake bake model``) ? Does it trigger you an error ?

Because I can't reproduce the issue with CakePHP 3.1.3 & migrations plugin 1.4

**Comment by YassineKhadouch** [comment]
i can bake everything (controller,model,template)

**Comment by YassineKhadouch** [comment]
should i print my composer json file here

**Comment by HavokInspiration** [comment]
That could help. As well as the full ``composer show -i`` output.
Some more context could help reproduce the issue as well : 

- is it from a fresh install ? 
- was it after a composer update ? 
- how did you install the migrations plugin ?

Anything that could help us reproduce the issue. Right now on a fresh install and on an already existing install, I can not seem to be able to reproduce the issue.

**Comment by YassineKhadouch** [comment]
--------------------------------------------   composer show -i  ---------------------------------------------
aura/installer-default            1.0.0          Installs Aura packages using the Composer defaults.
aura/intl                                1.1.1          The Aura.Intl package provides internationalization (I18N) tools, speci...
cakephp/bake                       1.1.1          Bake plugin for CakePHP 3.0
cakephp/cakephp                  3.1.3         The CakePHP framework
cakephp/debug_kit                3.2.2         CakePHP Debug Kit
cakephp/migrations               1.4                Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer         0.0.12             A composer installer for CakePHP 3.0+ plugins.
dnoegel/php-xdg-base-dir      0.1                implementation of xdg base directory specification for php
ircmaxell/password-compat   v1.0.4             A compatibility library for the proposed simplified password hashing al...
jakub-onderka/php-console-color             0.1                
jakub-onderka/php-console-highlighter    v0.3.2             
jdorn/sql-formatter                          v1.2.17            a PHP SQL highlighting library
mobiledetect/mobiledetectlib          2.8.17             Mobile_Detect is a lightweight PHP class for detecting mobile devices. ...
nesbot/carbon                         1.13.0             A simple API extension for DateTime.
nikic/php-parser                      v1.4.1             A PHP parser written in PHP
psr/log                                  1.0.0              Common interface for logging libraries
psy/psysh                             v0.5.2             An interactive shell for modern PHP.
robmorgan/phinx                       dev-master 43313ad Phinx makes it ridiculously easy to manage the database migrations for ...
symfony/config                          v2.7.6             Symfony Config Component
symfony/console                       v2.7.6             Symfony Console Component
symfony/filesystem                    v2.7.6             Symfony Filesystem Component
symfony/var-dumper                  v2.7.6             Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                             v2.7.6             Symfony Yaml Component
------------------------------------------------------------------------------------------------------------
--------------------- composer.json ---------------------
{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "http://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.4.16",
        "cakephp/cakephp": "~3.1",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "*"
    },
    "require-dev": {
        "psy/psysh": "@stable",
        "cakephp/debug_kit": "~3.2",
        "cakephp/bake": "~1.1"
    },
    "suggest": {
        "phpunit/phpunit": "Allows automated tests to be run without system-wide install.",
        "cakephp/cakephp-codesniffer": "Allows to check the code against the coding standards used in CakePHP."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests",
            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump"
    },
    "extra": {
    	"installer-paths": {
        "cakedc/migrations" : "./vendor/cakephp/migrations"
	}
    },
    "require": {
    "composer/installers": "*",
    "cakedc/migrations" : "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
------------------------------------------------------------------------
is it from a fresh install ?  
   YES
was it after a composer update ? 
   YES  (sudo /usr/local/bin/composer self-update)
how did you install the migrations plugin ? 
   I didn't install it since i am using cakephp 3 it is already included in vendor directory
---------------------------   cakephp-plugins.php content   ----------------------------
<?php
$baseDir = dirname(dirname(__FILE__));
return [
    'plugins' => [
        'Bake' => $baseDir . '/vendor/cakephp/bake/',
        'DebugKit' => $baseDir . '/vendor/cakephp/debug_kit/',
        'Migrations' => $baseDir . '/vendor/cakephp/migrations/'
    ]
];
--------------------------------------------------------------------------------------------------------
PHP Version: 5.4.42

**Comment by HavokInspiration** [comment]
Why do you have references to the cakedc/migrations plugins in your composer file ? (in the ``extra`` statement and in a second ``require`` statement)

This might be causing the issue.
Try removing them, removing the cakedc plugin and dumping the autoload file again.

**Comment by YassineKhadouch** [comment]
i was testing that plugin and i forgot to clean that out, but what it is weird is that it is working now without even cleaning the composer file, i don't now the cause of this but it is working now thanks for your help

**Comment by HavokInspiration** [comment]
Ok. Nice to know it's working for you now !
