### ISSUE TITLE
Issue with bake when trying to add field name starting with "To"

### ISSUE THREAD

**Issue by choma** [cakephp/migrations#147]
When I try to add a column named "token" to the Users table like this:

    bin/cake bake migration AddTokenToUsers token:string

bake generate this code:

``` php
public function change()
{
    $table = $this->table('ken_to_users');
```

Then, when I try to run the migration I get
```
[RuntimeException]                         
  Cannot update a table that doesn't exist!
```

It works if I do it this way:

    bin/cake bake migration AddtokenToUsers token:string

**Comment by antograssiot** [comment]
fixed in  #148

**Comment by acjbizar** [comment]
It appears this is still the case when the **second** part of a column name starts with `To`. I just noticed this running the following instruction:

```shell
cake bake migration --plugin DeZelf AddConfirmationTokenToUsers confirmation_token:string?[191]
```

**Comment by othercorey** [comment]
@acjbizar Please open a new issue.
