### ISSUE TITLE
File name closer to real class name?

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#152]
Is there any way we can make the class name closer to the real class name?
E.g. with "Init" the class name becomes `class Init extends AbstractMigration {}`, but the filename is `20151114132749_init.php`

CS tools lowercase the class name otherwise (or report an issue here).

So it would be better if the produced file name was at least `20151114132749_Init.php`.

**Comment by HavokInspiration** [comment]
It's worth checking, but I remember phinx being really picky (and a pain) about filename resolution.

**Comment by dereuromark** [comment]
We should maybe open a ticket there. But IMO its the PSR standard to always name your classes the same way as the file name and vice versa.

**Comment by HavokInspiration** [comment]
Note that removing the timestamp will not be possible based on how phinx currently works though.

But for the "text" part, it might already work though, I know the method for checking if the filename matches phinx requirements was changed not so long ago to a regex based approch, so it might be working. We would only need to change the filename generation then.

**Comment by dereuromark** [comment]
Removing the timestamp is not what is necessary :)
Only the uppercase of the "i" here in my example is.

**Comment by ionas** [comment]
I am not sure if that's worth it. I'd rather go with timestamp_class_to_lower_case as that is easier to type and it is an interface you would "type" against (including, untested: auto complete). In case this change is done, it should reflect a full CameCase classname not just the first char uppercase ;-).

**Comment by dereuromark** [comment]
Thats exactly what I meant, of course its full CamelCase!

**Comment by HavokInspiration** [comment]
I tested this a bit in a test-app, it apparently works OK.
I'll dig deeper when I have the time to see if just changing the snapshot naming strategy is enough to achieve this.

**Comment by HavokInspiration** [comment]
PR opened #175
