### ISSUE TITLE
MigrationSnapshotTask::tableToAdd not working well with plugins

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/migrations#163]
Hello. Say I have a plugin named `Vendor/Thing` and I want to make an initial snapshot of the tables in the datasource for that plugin. Right now, this is creating an empty migration file in my plugin.
```
bin/cake bake migration_snapshot -c datasource -p Vendor/Thing Initial
```

`MigrationSnapshotTask::tableToAdd` assumes that the table names are prefixed with the plugin name.

```
$tableName = 'posts';
$pluginName = 'Vendor/Thing';
$pluginName = strtolower(str_replace('/', '_', $pluginName)) . '_';
$shouldAdd = (strpos($tableName, $pluginName) !== false);
```

Why does it assume my table is named `vendor_thing_posts`? In my opinion, `tableToAdd` isn't really needed since it forces users to adhere to a non-documented naming convention. Is there a critical reason that method exists?

Thanks!
Patrick

**Comment by HavokInspiration** [comment]
I kind of understand why there is such a rule : to prevent collision between app table and plugins table.
But as you said, the rule is not really documented. 
So I kind of agree : we could very well remove this, given than the tables list is first computed by browsing through the model files from the plugin directories.

**Comment by lorenzo** [comment]
I agree it should be removed

**Comment by patrickconroy** [comment]
Closing with PR.
