### ISSUE TITLE
Migration Snapshot isn't exporting decimal fields correctly

### ISSUE THREAD

**Issue by fullybaked** [cakephp/migrations#168]
We started to use migrations with an existing database, so used the `bake migration_snapshot` command as per the [docs][1].  However using this migration to build our test database on our CI platform, broke the builds.  This is due to decimal fields being exported incorrectly

To reproduce:

Create a table as follows
```
CREATE TABLE `projects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fee_percentage` decimal(7,6) DEFAULT '0.150000'
  PRIMARY KEY (`id`),
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
```

Export it using the `bin/cake bake migration_snapshot Initial` command

Review the code and see the field definitions are incorrect 

```
        $table = $this->table('projects');
        $table
            ->addColumn('fee_percentage', 'decimal', [
                'default' => 0, // this is not the default value
                'limit' => 7, // this will not create a 7,6 decimal field
                'null' => true,
            ])
            ->create();
```

I think part of the problem is that precision isn't handled in the bake template in migrations plugin in the `wantedOptions` array.  [here][2]

Plus as you are casting default values to int's in the Migration helper, you can't have decimal values as defaults in these cases. [here][3]

[1]: http://book.cakephp.org/3.0/en/migrations.html#generating-migrations-from-existing-databases

[2]: https://github.com/cakephp/migrations/blob/master/src/Template/Bake/config/snapshot.ctp#L16

[3]: https://github.com/cakephp/migrations/blob/master/src/View/Helper/MigrationHelper.php#L264

**Comment by Penergy** [comment]
I use this:
->addColumn('weight', 'decimal', [
            'default' => null,
            'null' => false,
            'precision' => 10, 
            'scale' => 1,
            'signed' => 'unsigned'
        ])

**Comment by HavokInspiration** [comment]
Closing as PR has been opened.
