### ISSUE TITLE
Did anyone has the problem to migrate a specific version table?

### ISSUE THREAD

**Issue by Penergy** [cakephp/migrations#171]
bin/cake migrations migrate -t 20150103081132

From the cookbook, I tried to use the above code. But it did not update the specific migration file.

Did anyone face and solve this problem?

**Comment by HavokInspiration** [comment]
Using the ``-t`` option will migrate all migrations **up to** the one you specified (so from the last that was migrated to the one specified).

**Comment by Penergy** [comment]
Thx @HavokInspiration, I hope next version has this function.

**Comment by HavokInspiration** [comment]
I'll open a RFC to gather opinions on the feature.
