### ISSUE TITLE
Generating Migrations From Existing Databases In plugin fail

### ISSUE THREAD

**Issue by markstory** [cakephp/migrations#172]
_From @visonforcoding on December 15, 2015 7:32_

I want  generating migrations to the plugin config dir from existing database,
when i use the command
```
bin/cake bake migration_snapshot --plugin Admin Initial

```
Admin is my plugin .
the migrations file has been created .bug the up and down function is empty!

_Copied from original issue: cakephp/cakephp#7851_

**Comment by markstory** [comment]
_From @lorenzo on December 15, 2015 9:33_

Can you please open the issue report in this repo? https://github.com/cakephp/migrations

**Comment by visonforcoding** [comment]
yes,thank you @markstory

**Comment by HavokInspiration** [comment]
@visonforcoding What are your CakePHP and migrations plugin versions ?

**Comment by visonforcoding** [comment]
@HavokInspiration  My CakePHP version is 3.1.5  .both version are the newest .

**Comment by HavokInspiration** [comment]
Can you give us more details about your plugin ?
Does it define any ``Table`` classes ?
Do you have specific tables linked to that plugin ?

Can you provide us with some source code / table schemas for which the error occures ? Anything that can help us reproduce the issue you are having.

**Comment by visonforcoding** [comment]
@HavokInspiration  My plugin just a website backend manager plugin. yes ,I defiend table class.a admin table that stored manager info username and password and so on. This table can be created right migration file in the root config dir when i use command:
```
bin/cake bake migration_snapshot Initia
```
But this table is my plugin table,i want it can reuseable . I want table migration file can be created in the plugin config dir .so i use the "-- plugin " parameter. The migration file has been created but there is nothing in the up and down function.Command work well in root dir but not in my plugin . i got two empty function .

**Comment by HavokInspiration** [comment]
@visonforcoding PR https://github.com/cakephp/migrations/pull/153 should have fixed the issue you are raising. I'll run some more tests to see it there are some use cases missing.

**Comment by HavokInspiration** [comment]
Ok, I can reproduce the issue. PR #153 did fix the issue, but only if the command was run with the ``--require-table`` flag

**Comment by HavokInspiration** [comment]
PR #174 opened.
