### ISSUE TITLE
Bake not generating migration code

### ISSUE THREAD

**Issue by mistaguy** [cakephp/migrations#187]
As a user who is on windows 10 using powershell
When i run any migration bake command
the code is not generated. 

the example below shows that the file was written but i see nothing

<pre>
<code>

C:\xampp\htdocs\aline-ims> bin/cake bake migration AddUsernameUniqueToUsers username:string:unique

Welcome to CakePHP v3.1.6 Console
---------------------------------------------------------------
App : src
Path: C:\xampp\htdocs\aline-ims\src\
PHP : 5.4.19
---------------------------------------------------------------

Creating file C:\xampp\htdocs\aline-ims\config\Migrations\20160120211428_AddUsernameUniqueToUsers.php
Wrote `C:\xampp\htdocs\aline-ims\config\Migrations\20160120211428_AddUsernameUniqueToUsers.php`
</code>
</pre>

**Comment by josegonzalez** [comment]
So you are saying that file doesnt exist for you?

**Comment by mistaguy** [comment]
It creates the migration file but its empty with no code

**Comment by josegonzalez** [comment]
Interesting. That works fine for me on php 5.6.16 on a Mac. What version of PHP are you using?

**Comment by mistaguy** [comment]
see above PHP : 5.4.19

**Comment by josegonzalez** [comment]
@dereuromark can you check this out? Maybe its an issue regarding PCRE on windows?

**Comment by dereuromark** [comment]
If I run that on my Win10 machine on normal shell, I get:
```php
class AddUsernameUniqueToUsers extends AbstractMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-change-method
     * @return void
     */
    public function change()
    {
        $table = $this->table('users');
        $table->addColumn('username', 'string', [
            'default' => null,
            'limit' => 255,
            'null' => false,
        ]);
        $table->addIndex([
            'username',
        ], [
            'name' => 'UNIQUE_USERNAME',
            'unique' => true,
        ]);
        $table->update();
    }
}
```

**Comment by mistaguy** [comment]
I have run on a normal shell and still the issue is there. I have checked permission and Everyone has access. I will keep investigating and give feedback

**Comment by HavokInspiration** [comment]
Interesting. First thing that comes to my mind would be the ``:`` used  causing problem. I know I had problems with some special characters in the past.
Can you try the following command and tell us what you get ?

``bin/cake bake migration AddUsernameUniqueToUsers username``

Another queston : do you have the column ``username`` already created in your schema ?

**Comment by josegonzalez** [comment]
@mistaguy friendly *bump* :)

**Comment by HavokInspiration** [comment]
Closing as there was no feedback on this.
I'll reopen if anything new comes up.
