### ISSUE TITLE
Data seeding shell

### ISSUE THREAD

**Issue by TamiasSibiricus** [cakephp/migrations#19]
Just another idea.
How about to implement data seeding shell for this plugin.
Data can be stored in /config/Data in app or plugin folder.
I think all data must be in actual state for last migration.
Data seeding process cna't start if migration is not complete.
What do you think?

**Comment by sdustinh** [comment]
Ref: http://docs.phinx.org/en/latest/seeding.html

**Comment by beporter** [comment]
Everyone's situation is going to be different obviously, but my team and I ended up writing a Cake plugin to do data seeding. It still isn't tied to specific migrations, but there's no reason it couldn't be (just have your migrations `after()` invoke the appropriate Shell command and seed file name).

Anyway, here's another alternative in case it's useful to anyone that finds this thread:

https://github.com/loadsys/CakePHP-Basic-Seed

**Comment by kingsolmn** [comment]
Would love to see this implemented, would be a whole lot easier!

Ref: @sdustinh http://docs.phinx.org/en/latest/seeding.html

**Comment by josegonzalez** [comment]
@beporter I'd love to somehow have the following feature implemented for the CakePHP ORM: [data-seeding from a production database](https://github.com/IFTTT/polo/). Maybe something you guys at Loadsys can investigate ;)

**Comment by justinatack** [comment]
You can still use the built in Phinx data seeding classes in your change() or up() methods. It would be nice though if we could bake separate Seeding files.

```
$data = [
    [
        'name' => 'Return of the Jedi',
        'series' => 'VI'
    ],
    [
        'name' => 'The Force Awakens',
        'series' => 'VII'
    ]
];

$this->table('movies')
       ->insert($data)
       ->save();
```

**Comment by josegonzalez** [comment]
What would be the initial seed data? Just empty?

**Comment by sdustinh** [comment]
I've been using the TableRegistry in the up() method with a migration file prefixed like 'SeedRoles'. Honestly the only complaint I have with this method is that it marks the migration as migrated. If I could toggle that behavior I'd be set.

**Comment by HavokInspiration** [comment]
With the support of seeders added to phinx and the migrations plugin enhancements following this, I think this can be closed.
