### ISSUE TITLE
An issue with creating seed

### ISSUE THREAD

**Issue by clthck** [cakephp/migrations#190]
I populated 5 rows in my `users` table. But when I create seed file using `cake bake seed Users`, the `UsersSeed.php` file is generated with empty `$data` array. Is there anything I missed for creating seeds?

**Comment by HavokInspiration** [comment]
Currently, the seed baking feature does not fetch the data in the table, it just creates an empty skeleton to ease the process of creating a Seed class.
You will have to add the data manually for now.

But what you suggesting is something I had in mind, I was planning to open a RFC to talk about it and gather people opinions on this (as well as discuss potential problems such as FK constraints).

**Comment by clthck** [comment]
thanks for your response. I'll look forward to this feature for next release.

**Comment by HavokInspiration** [comment]
It might not make it to the next release though, it needs more discussion first.

I opened a RFC to discuss this : #191.
