### ISSUE TITLE
Baking a seed file with data from the database

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/migrations#191]
Following #190, I'm opening this RFC to gather opinions around enhancing the seed baking feature to extract data from the database to be included in the created seed file.

The first idea of an implementation I had was to add an interactive part to the baking process, asking the dev, if there are records in the table, if he/she wants to do an extract of the data and include it in the seed file.
While it seems easy, there are a two cases I'd like to discuss first :

**A high number of records**
Let's say I am baking a seed file for a table where there are 10k records, how should it behave ? Clearly we shouldn't shove all the records in the seed file. Do we add another interactive part where we ask the dev to provide the PK of the records he/she wants to be included ?

**Foreign key constraints**
Let's say I have two tables : ``articles`` and ``users``, where ``articles`` has a column ``user_id`` which is a constraint referencing the column ``users.id``. If I bake only a seed file for the ``articles`` table, it could result in an error when seeding the db in some cases (the ``users`` table is empty for instance). Should we detect the FK during the baking process and ask the user if he/she wants the records from the FK to be included as well to avoid problems ?

Those are the only problems I foresee right now.
Do you have any opinion on this possible enhancement ? Is it something you could use ? Any ideas around those two issues ? Any other issue you can foresee ?

**Comment by josegonzalez** [comment]
Relevant: https://gist.github.com/josegonzalez/3863f341ede1b6273ba3

**Comment by HavokInspiration** [comment]
Looks like you already gave this some thoughts.
Thanks for the link, I'll study this in depth later.

In that current state and with the seed feature implemented, do you think that is usable with baking a seed ?

**Comment by josegonzalez** [comment]
I think so, needs lots of tests.

One thing to note is that some databases - postgres for instance - won't update the auto-increment field if you insert with an id already set. Something to think about (I can add the option to remove the `id` from my library).

Foreign keys are a problem, for sure. We should probably just warn the users, no sense in my head to make this the be-all-end-all tool. Is there a way to output a `warning` message from within a seed? That way we can just generate seed files with the warnings already set.

**Comment by HavokInspiration** [comment]
> One thing to note is that some databases - postgres for instance - won't update the auto-increment field if you insert with an id already set

Or we could execute a query to update the sequence field manually. But there could be downside with this I don't know about.

> Is there a way to output a warning message from within a seed?

Yes. The AbstractSeed class we extend has a protected $output property accessible through a getter : https://github.com/robmorgan/phinx/blob/0.5.x-dev/src/Phinx/Seed/AbstractSeed.php#L103-L115

**Comment by josegonzalez** [comment]
You may want to look into the ifttt/polo project, which my set of scripts is based on.

**Comment by lorenzo** [comment]
Removing the id will be tricky as well, I think updating the sequence is the best idea

**Comment by josegonzalez** [comment]
We should warn and require people to accept or force the seed to run if it is "generated" from the database imo.

**Comment by HavokInspiration** [comment]
#260 implements this.
