### ISSUE TITLE
Unsigned missing in migration_snapshot

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/migrations#197]
I have a table where (for whatever reason) all primary keys are `INT(11) UNSIGNED`.

This is not honored in the output of migration_snapshot. It is also not honored for foreign keys or, as a matter of fact, for any columns. See an example in #196.

**Comment by HavokInspiration** [comment]
I'll take care of it.

**Comment by HavokInspiration** [comment]
PR #198 opened.

**Comment by ypnos-web** [comment]
I found that after this fix, my primary keys where correct in the snapshot (option `'signed' => false` is present), but my foreign keys weren't.

This led into an inconsistent snapshot that also failed to apply because of the foreign key being incompatible to the primary key of the other table.
