### ISSUE TITLE
Fatal error, migrations not working

### ISSUE THREAD

**Issue by CodeBlastr** [cakephp/migrations#202]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2
* Migrations plugin version: a8f3eb8065bb516cd7349ed50daffc559aa10347
* Bake plugin version (if relevant): 78c53a1
* Database server (MySQL, SQLite, Postgres): MySql
* PHP Version: 5.5
* Platform / OS: Nginx / Mac

### What you did

trying to run pretty much any migrations command from shell (specifically "migrate" or "status" or "create") and tried the -p flag. 

### Expected Behavior
That a migration would create the users table, or create a user migration file if I create my own users table. 

### Actual Behavior
Nothing happens, I just get this message : Fatal error: Class Migrations\CakeAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Phinx\Db\Adapter\AdapterInterface::getVersionLog) in /Applications/nginxstack-1.9.10-0/apps/[domain name]/htdocs/vendor/cakephp/migrations/src/CakeAdapter.php on line 670

**Comment by thiagosrios** [comment]
The same thing is happening to me. 

* CakePHP Version: 3.1.11.
* Migrations plugin version: 1.5.6.
* Bake plugin version: 1.1.
* Database server (MySQL, SQLite, Postgres): Postgres
* PHP Version: 5.4.31
* Platform / OS: Apache / Windows 7 (Work enviroment)

**Comment by AnderWeb** [comment]
Sorry, I made the report on the wrong repo.

As I said in my duplicate report, the issue is cause of the new Phinx interface method in [this commit](https://github.com/robmorgan/phinx/commit/3dbbbcec9acd945cc6b16afd8d68e0076ab266fd)

**Comment by HavokInspiration** [comment]
PR #204 opened to address this issue.

**Comment by HavokInspiration** [comment]
A new release has been tagged.
If you do a ``composer update``, this should upgrade the plugin to the new release and rollback phinx version to 0.5.1 and everything should be working again.

**Comment by AnderWeb** [comment]
Any way we can track when the Phinx 0.5.2 will be supported? They included some new things like support for creating full-text indexes that are quite welcome.

**Comment by HavokInspiration** [comment]
A release will be made when support for phinx 0.5.2 will be added.
You can be notified of new releases (and opened Pull Request) by "watching" the repository.
