### ISSUE TITLE
migration_snapshot generated file, throws error when applying the migration

### ISSUE THREAD

**Issue by CodeBlastr** [cakephp/migrations#207]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2
* Migrations plugin version: cb8c82a
* Bake plugin version (if relevant): 02a9443
* Database server (MySQL, SQLite, Postgres): Postgres 9.5.1
* PHP Version: 7.0
* Platform / OS: Mac OS X Yosemite 10.10.5

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

1. ran the command ``bin/cake bake migration_snapshot Initial --plugin VendorName/PluginName``
2. dropped all the database tables (to prep for a test of rebuilding them)
3. ran the command ``bin/cake migrations migrate -p VendorName/PluginName``

### Expected Behavior
I figured that an export, straight to import would simply recreate the database tables that were exported. 

### Actual Behavior
Received the error : ``[PDOException] SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "active" is of type boolean but default expression is of type integer``

Screenshot : https://www.evernote.com/shard/s13/sh/5a1f9f0d-a95b-4c12-964d-b173979198f4/921ee734763ad5efefdf9b8c151d6f5b

P.S. If I change the 0 to false in this screen shot it imports correctly : https://www.evernote.com/shard/s13/sh/ff2544e6-9704-4f25-8ff0-b5bdd7d09f44/652ed7795bed05554fa6046606e3791d

P.S.2. Even if I change it to false, and do the import with working values, then immediately export, the export still gives 0 instead of false, and thus won't import.  (eg. an import to export to import doesn't work)

**Comment by HavokInspiration** [comment]
Thanks for the detailed informations.
We will look into it.

**Comment by HavokInspiration** [comment]
PR #208 opened.
