### ISSUE TITLE
Custom database seeding

### ISSUE THREAD

**Issue by markstory** [cakephp/migrations#212]
_From @tolawho on March 29, 2016 9:37_

This is a (multiple allowed):
* [x] feature-discussion (RFC)

In `Laravel`, I easy seed database with any seeders and any order i want.
![screenshot_2](https://cloud.githubusercontent.com/assets/12527881/14103484/9f796d04-f5ca-11e5-9ecd-69b820c301d5.png)

But, `Cakephp ` will run all available seeders in the target directory and only support in alphabet order. That was inconvenient.

_Example _ In `Laravel`: I run `CitiesSeeder` after `CountriesSeeder ` because I need `country_id ` insert to `cities ` table. 
 
![screenshot_3](https://cloud.githubusercontent.com/assets/12527881/14103870/5178b1ee-f5cc-11e5-8ee1-c226c3066212.png)

_Copied from original issue: cakephp/cakephp#8559_

**Comment by markstory** [comment]
_From @burzum on March 29, 2016 10:53_

Having seeds that can't rely or depend on each other makes them useless for some scenarios.

So :+1: from me.

**Comment by HavokInspiration** [comment]
This should indeed be more convenient.
It is under discussion in phinx : https://github.com/robmorgan/phinx/issues/737

Depending on how it is done (and how fast it is done) on phinx side, we could always implement it our way.

**Comment by HavokInspiration** [comment]
Since phinx has been stale for month, I started working on this.
I have a base implementation working but it needs some more work to make the output less verbose.

**Comment by HavokInspiration** [comment]
I opened PR #236 to implement the feature.
