### ISSUE TITLE
Support namespaces in migration files.

### ISSUE THREAD

**Issue by markstory** [cakephp/migrations#213]
_From @thinkingmedia on April 7, 2016 13:8_

This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.2.6
- Platform and Target: Apache2, MySQL, PHP 7
### What you did
- Create an app and bake a migration file called `CreateImages`.
- Create a plugin and bake a migration file called `CreateImages`.
### Expected Behavior

The classes `CreateImages` are unrelated to each other.
### Actual Behavior

PhpStorm warns that the class `CreateImages` is already defined for the project. Since the migration classes do not use a namespace they exist in the same global space.

Is this a limitation imposed by Phinx?

_Copied from original issue: cakephp/cakephp#8603_

**Comment by markstory** [comment]
_From @dereuromark on April 7, 2016 13:16_

If this is a limitation maybe we should always prefix with the plugin or vendor name then?

**Comment by markstory** [comment]
_From @thinkingmedia on April 7, 2016 13:34_

I would prefix only plugins but that's a good idea.

**Comment by markstory** [comment]
_From @HavokInspiration on April 7, 2016 17:12_

Right now, migrations can not live under a namespace.
See https://github.com/cakephp/migrations/issues/139 and https://github.com/robmorgan/phinx/issues/168

So currently, only prefixing the migration classname as @dereuromark suggested would work.

**Comment by dereuromark** [comment]
:+1: for namespaces and alike. I ran into the same issue now a few times with too short names and thus colliding with basic classes of the app.

**Comment by thinkingmedia** [comment]
In addition to namespaces. I wish we could file migrations under subfolders where a folder presented a major version. I have been struggling with a large number of migration files that I don't want to throw away as I sometimes build from scratch on my dev machine, but after working on this project for several years. A single folder approach shows the a lack of scalability.

**Comment by dereuromark** [comment]
We first need to fix up Phinx here in https://github.com/cakephp/phinx/issues/168
