### ISSUE TITLE
Failed migrations should not return exit code 0

### ISSUE THREAD

**Issue by steinkel** [cakephp/migrations#215]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3
* Migrations plugin version: 1.5.7
* Bake plugin version (if relevant): not relevant
* Database server (MySQL, SQLite, Postgres): not relevant
* PHP Version: PHP 5.6.11-1ubuntu3.1
* Platform / OS: Ubuntu 15.10

### What you did
Run a migration getting an exception while deploying the application, the deploy script continued because the exit code returned by migrations was 0

### Expected Behavior
Failed migrations (exception) should return exit code != 0

### Actual Behavior
Failed migrations (exception) return exit code === 0

**Comment by thinkingmedia** [comment]
This issue exists for seeding as well.

**Comment by HavokInspiration** [comment]
@thinkingmedia That normal since migrating and seeding goes through the same shell class.

PR #224 opened.
