### ISSUE TITLE
Unable to bake migration

### ISSUE THREAD

**Issue by plan8studios** [cakephp/migrations#226]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.9
* Migrations plugin version: 0.4.1
* Bake plugin version: 1.1
* Database server: MySQL Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.3
* PHP Version: PHP 5.6.14-1+deb.sury.org~trusty+1
* Platform / OS: Ubuntu 14.04.3 LTS

### What you did
Tried to `bake` a migration like so:
```bin/cake bake migration CreateUsers id:uuid:primary name:string email:string:unique password:string reset_hash:string[32] role:string[20] created modified deleted:datetime```

Full output available here - https://gist.github.com/plan8studios/2bd2ecbfceae7dfbe7977ab7c80d66f9

### Expected Behavior
The migration should be created with a bunch of `$table->addColumn` and `$table->addIndex` calls.

### Actual Behavior
The migration is throwing an exception of "Too many arguments" and not being created.

**Comment by HavokInspiration** [comment]
This is a regression introduced by #222. 
PR #227 was opened to fix it.

**Comment by HavokInspiration** [comment]
Migrations 1.6.1 released. It should fix the problem.
