### ISSUE TITLE
Fatal error with abstract table class before migrations run

### ISSUE THREAD

**Issue by segy** [cakephp/migrations#229]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.9
* Migrations plugin version: 1.6.0
* Bake plugin version (if relevant): not relevant
* Database server (MySQL, SQLite, Postgres): MySQL 5.6.28
* PHP Version: 5.6.14-0+deb8u1
* Platform / OS: Debian 8.2

### What you did
I have an abstract table class located in src/Model/Table (it acts as parent for several tables)

### Expected Behavior
Nothing special. I expect migrations to run without error as it did before 1.6.0

### Actual Behavior
Actual behavior from 1.6.0 gives me this error:
PHP Fatal error:  Cannot instantiate abstract class ...\Model\Table\BaseOrdersTable in .../vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php on line 207

It is not that fatal at all, since migrations run without error. Just there is this error before migrations actually run.

**Comment by HavokInspiration** [comment]
Interesting.
Everything operates normally except for this error ? And everything worked fine with 1.5.8 ?

I'll look into it to see if I can reproduce.

**Comment by HavokInspiration** [comment]
Can you give me specifics ?
Class examples, migration files examples... anything that can help me reproduce the issue, because I've had no luck so far.
Thanks !

**Comment by segy** [comment]
Hello 

sorry for late response. I tried it simply on fresh copy of `cakephp/app`.

Create two files in src/Model/Table:

```php
// TestsBaseTable.php
namespace App\Model\Table;

use Cake\ORM\Table;

abstract class TestsBaseTable extends Table
{
}

// TestsTable.php
namespace App\Model\Table;

class TestsTable extends TestsBaseTable
{
}
```

When you run `bin/cake migrations migrate` output is:

```
Welcome to CakePHP v3.2.9 Console
---------------------------------------------------------------
App : src
Path: .../src/
PHP : 5.6.14
---------------------------------------------------------------
using migration path .../config/Migrations
using seed path .../config/Seeds
using environment default
using adapter mysql
using database test

All Done. Took 0.0005s
using migration path .../config/Migrations
using seed path .../config/Seeds
PHP Fatal error:  Cannot instantiate abstract class App\Model\Table\TestsBaseTable in .../vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php on line 207

Fatal error: Cannot instantiate abstract class App\Model\Table\TestsBaseTable in .../vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php on line 207
```

**Comment by thinkingmedia** [comment]
I have an abstract `AppTable` class in my app and migrations run fine.

**Comment by thinkingmedia** [comment]
In your migration output it looks like it's running a second time. Why is there output after `All Done. Took 0.0005s`

Do you have more than one data source?

**Comment by segy** [comment]
As I said, I created a new project using `composer create-project cakephp/app` and added only these two files. Nothing more. So I hope it's easily reproduceable.

**Comment by HavokInspiration** [comment]
Thanks. I'll give it a look with the extra informations.
It probably comes from the new ``dump`` command that is executed after a ``migrate`` or a ``rollback`` command and creates the comparison file for the new diff feature (which would explain why it gives the impression to run twice, since the shell is dispatched).

**Comment by HavokInspiration** [comment]
PR #231 opened to fix that.

**Comment by segy** [comment]
thanks
