### ISSUE TITLE
autoIncrement option error

### ISSUE THREAD

**Issue by ADmad** [cakephp/migrations#238]
_From @dereuromark on June 8, 2016 9:22_

Yesterday, `bin/cake` bake migration_snapshot baked:

```
        $this->table('users')
            ->addColumn('id', 'integer', [
                'autoIncrement' => true,
                'default' => null,
                'limit' => 10,
                'null' => false,
                'signed' => false,
            ])
```

Running migrations migrate afterwards on a fresh db table gets:

```
 == 20141125043024 Init: migrating
  [RuntimeException]
  "autoIncrement" is not a valid column option.
```

Also `->addPrimaryKey(['id'])` is unknown and errors.
Did someone forget the  constraints of the phinx dependency to set them up?

Latest stable and dev master of this plugin are affected.

Tested with MySql.

_Copied from original issue: cakephp/bake#255_

**Comment by ADmad** [comment]
_From @HavokInspiration on June 8, 2016 12:9_

Wrong repo ?

**Comment by ADmad** [comment]
_From @dereuromark on June 8, 2016 12:13_

Darn. Yeah

But actually I baked it, so it was invalid bake code result - so maybe related to this repo as well?

**Comment by HavokInspiration** [comment]
Nop, it's only related to the migrations plugin.
Can you please provide the schema db that's doing the wrong bake file ?

**Comment by HavokInspiration** [comment]
And the full output of the bake file as well

**Comment by dereuromark** [comment]
```
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_id` int(10) unsigned DEFAULT NULL,
  `status` int(2) NOT NULL DEFAULT '0',
  `last_login` datetime DEFAULT NULL,
  `last_online` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `logins` int(10) unsigned NOT NULL DEFAULT '0',
  `username` varchar(30) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(80) NOT NULL,
  `email_confirmed` tinyint(1) NOT NULL DEFAULT '0',
  `gender` int(2) unsigned DEFAULT NULL,
  `session_expired` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;
```

**Comment by dereuromark** [comment]
Ah I moved it from up() to change() which might have broken it
Why are we not using change() right away, which seems to be a bit more useful as it provides down() automatically with it?

**Comment by HavokInspiration** [comment]
What I did :

- ``composer create`` a new app
- set up a db with the schema you provided
- ``bin/cake bake migration_snapshot Initial``

Got the following result : https://gist.github.com/HavokInspiration/48a23dba1af3b9b458856e711eb4f33f

Can you provide more details on your setup ?

As for your question about up/down versus change, it is mostly to better deal with FK constraints.

**Comment by dereuromark** [comment]
When having compose update everything clean (and tmp cleared)
I also get
```
Warning Error: Invalid argument supplied for foreach() in [...\tmp\bake\Bake-config-snapshot-ctp.php, line 42]

2016-06-09 12:40:51 Warning: Warning (2): Invalid argument supplied for foreach() in [...\tmp\bake\Bake-config-snapshot-ctp.php, line 42]
Trace:
```

**Comment by HavokInspiration** [comment]
Yeah, I fixed that already in another PR.
I thought I tagged the release but it seems I forgot 😄 Will do it tonight if I get the time.

But even with a clean app, what does the generated file look like ?

**Comment by HavokInspiration** [comment]
@dereuromark With a brand new app, warning in the terminal aside that will be fixed when 1.6.2 rolls out, what does the complete generated file looks like ?

**Comment by dereuromark** [comment]
I just wait for the new release and maybe its all good then.

**Comment by HavokInspiration** [comment]
@dereuromark 1.6.2 released just now

**Comment by HavokInspiration** [comment]
@dereuromark Same suggestion as for #245 : can you try clearing your bake cache ?

**Comment by HavokInspiration** [comment]
ping @dereuromark 

Is it still an issue ?

**Comment by davo3** [comment]
I am having the same issue. cake v3.3.8, migrations v 1.6.3

**Comment by thinkingmedia** [comment]
Closing as Phinx uses `identity` option to flag a column as auto increment.

```
For integer and biginteger columns:

Option	Description
identity	enable or disable automatic incrementing
signed	enable or disable the unsigned option (only applies to MySQL)
```

Reference:

http://docs.phinx.org/en/latest/migrations.html#valid-column-options
