### ISSUE TITLE
Create Migration File Warning Error

### ISSUE THREAD

**Issue by eAliwei** [cakephp/migrations#242]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version:3.2.10
* Migrations plugin version: 1.6.1
* Bake plugin version (if relevant): 1.2.4
* Database server (MySQL, SQLite, Postgres): MySQL 5.7.11
* PHP Version: PHP 7.0.7
* Platform / OS: OS X EI Capitan 10.11.6 Beta

### What you did
```bash
./bin/cake bake migration CreateProducts
```

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.
![image](https://cloud.githubusercontent.com/assets/6028737/16068036/e58dbb12-32f4-11e6-9382-4d6a5f4452cd.png)

**Comment by HavokInspiration** [comment]
I can not reproduce with plugin version 1.6.2 (just released).
Can you update and try again and tell me if it is still doing it ?

**Comment by HavokInspiration** [comment]
Mmm, I was able to reproduce by removing the ``@`` here in bake : 
https://github.com/cakephp/bake/blob/master/src/View/BakeView.php#L245

I'll check out if it is bake related or migrations related.

**Comment by HavokInspiration** [comment]
Did you define a error handler function using ``set_error_handler()`` ? (see http://php.net/manual/en/function.set-error-handler.php

If so did you deal with the case where ``error_reporting()`` returns 0 in your function ? (see http://php.net/manual/en/function.set-error-handler.php#112881)

That could explain why you are experiencing it.

**Comment by HavokInspiration** [comment]
@eAliwei Any update on this ?

**Comment by eAliwei** [comment]
@HavokInspiration Thanks
I closed xdebug extension
Warning disappears
