### ISSUE TITLE
New lock file is added to Migrations folder after migration.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/migrations#243]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Migrations plugin version: 1.6.1
* Database server (MySQL, SQLite, Postgres): MySQL v5.7.10
* PHP Version: PHP 7.0.3
* Platform / OS: Windows 10

### What you did

Run `bin/cake migrations migrate`

### Expected Behavior

Migration is performed without any changes to file system.

### Actual Behavior

A new file is added to `config/Migrations/schema-dump-NAME.lock` where "name" is the database name.

This is causing issues on my build server since it's an untracked artifact. This file started appearing after updating the plugin to 1.6.1

Not sure what this file is and it's not documented anyway (that I can find).

**Comment by lorenzo** [comment]
This is expected, add the file to our source control

**Comment by lorenzo** [comment]
I'll make a note in the book about it

**Comment by annuh** [comment]
@lorenzo Should this lock file be included in a .gitignore? 

I keep getting git conficts when I try to fetch my git repo on the productions servers, because a previous migrations changed the lock-file on the production-server.

**Comment by lorenzo** [comment]
I think we are missing a flag to run migrations without producing the lock file. This file should be, in my opinion, in version control, but it is definitely not ideal that it gets re-written in production for no reason.
