### ISSUE TITLE
Empty DB should not error

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#245]
If you got an empty table and latest release:

    bin/cake bake migration_snapshot Init

gets
```
Notice Error: Undefined index: dropForeignKeys 
in [/.../tmp/bake/Bake-config-snapshot-ctp.php, line 42]
```
and
```
Warning Error: Invalid argument supplied for foreach() 
in [/.../tmp/bake/Bake-config-snapshot-ctp.php, line 42]
```

**Comment by HavokInspiration** [comment]
Can you try clearing your bake cache ? 
I don't have such an error and it should be fixed with 1.6.2 with this commit : https://github.com/cakephp/migrations/commit/d1eae3a7ccbc7aec0fa4a90343f64f4100fb82fd

**Comment by HavokInspiration** [comment]
ping @dereuromark 
Is it still an issue ?

**Comment by dereuromark** [comment]
I will check later
