### ISSUE TITLE
Timestamp default value bug on OSX

### ISSUE THREAD

**Issue by half2me** [cakephp/migrations#247]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.11
* Migrations plugin version: 1.6.2
* Database server (MySQL, SQLite, Postgres): MySQL 5.7.13 (same error with older versions)
* PHP Version: 5.6.21
* Platform / OS: OSX 10.11.5

### What you did
I ran my migrations just as I would on any other system. (Works fine on travis container-based, and other linux systems I've tried it on).
Snippet from my migrations file:
```php
$table
            ->addColumn('created', 'timestamp', [
                'default' => 'CURRENT_TIMESTAMP',
                'limit' => null,
                'null' => false,
            ])
            ->addColumn('modified', 'timestamp', [
                'default' => null,
                'limit' => null,
                'null' => false,
            ])
```

### Expected Behavior
It works just fine everywhere else, and doesn't set a default value on the 'modified' column.

### Actual Behavior
On my OSX machine, it is giving me the following error:
```
[PDOException]                                                                                                      
    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'modified'   
```

It seems like its trying to set the `DEFAULT NULL` parameter, instead of just skipping it. And if null is not allowed, the default cannot be null. But even if I completely remove the ` 'default' => null,` part, the result is exactly the same.

Note: If I change the ` 'default' => null,` to ` 'default' => 'anything else',` it works just fine.

**Comment by HavokInspiration** [comment]
That is one weird issue.

I'll try to see if I can reproduce it on my work laptop. It might take some time, I have nothing set up locally on it. If anybody passing by and wants to take a look at this, this will be very welcomed.

**Comment by half2me** [comment]
@HavokInspiration IKR? I haven't tried dumping the SQL commands which get generated, frankly I'm kind of lost on how to do that, maybe if I enabled logging all queries on the server, I could post the commands that are being generated, and it might help.

**Comment by half2me** [comment]
So I just enabled query logging on my mysql, and here is what is being generated:
```sql
CREATE TABLE `packages` (`id` BIGINT(20) unsigned NOT NULL AUTO_INCREMENT, `client_user_id` BIGINT(20) unsigned NULL, `packager_user_id` BIGINT(20) unsigned NULL, `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `modified` TIMESTAMP NOT NULL, `comment` VARCHAR(255) NULL, `sent` DATE NULL, `product_count` INT(11) unsigned NOT NULL DEFAULT 0, PRIMARY KEY (`id`),  KEY (`client_user_id`),  KEY (`packager_user_id`)) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci
```
Which seems perfect to me. Yet the next query is a rollback, because this SQL fails even when I try to run in manually.
The server modes are (default 5.7 modes): `ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

**Comment by half2me** [comment]
Okay, so this is probably a bug in MySQL, not in migrations :) Sorry for the false alarm.

This query runs fine:
```sql
CREATE TABLE `packages` (
  `created`       TIMESTAMP           NOT NULL,
  `modified`      TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP
)
```
While this one fails with `[42000][1067] Invalid default value for 'modified'`:
```sql
CREATE TABLE `packages` (
  `created`       TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified`      TIMESTAMP           NOT NULL
)
```

**Comment by HavokInspiration** [comment]
Thank you for looking into it.

According to the answer given to your ticket, the problem comes from the ``explicit_defaults_for_timestamp`` setting in MySQL and strict mode which seems to be a default in 5.7.
So indeed not a problem with the plugin itself.
