### ISSUE TITLE
Making output formatting useful

### ISSUE THREAD

**Issue by sdustinh** [cakephp/migrations#250]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
- CakePHP Version: 3.2.11
- Migrations plugin version: 1.6.2
- Bake plugin version (if relevant): 1.2.4
- Database server (MySQL, SQLite, Postgres): MySQL 5.6.30
- PHP Version: 7.0.8
- Platform / OS: Ubuntu 14.04
### What you did

``` bash
sdustinh@claudia:~/github/app$ bin/cake migrations status -f json

Welcome to CakePHP v3.2.11 Console
---------------------------------------------------------------
App : src
Path: /home/sdustinh/github/app/src/
PHP : 7.0.8-3+deb.sury.org~trusty+1
---------------------------------------------------------------
using migration path /home/sdustinh/github/app/config/Migrations
using seed path /home/sdustinh/github/app/config/Seeds
using environment default
using format json
[{"status":"down","id":"20160525182515","name":"Users"}]
```

```
sdustinh@claudia:~/github/app$ bin/cake migrations status -f json --quiet
sdustinh@claudia:~/github/app$ 
```

My actual use case is that I am writing a `bin/cake migrate` shell that fires an event so that everything in my application can just hook into it and all migrations can be run in one command. This issue would also apply to something like `bin/cake migrations status -f json > status.json`.

There is just no way to make that json output useful without writing to a file and parsing through it. In my shell I use `Shell::dispatchShell($command)` but the way `ConsoleIo` is structured I have no non-hacky way to capture that output to process it myself which makes integration with the Migrations plugin very difficult.

According to the [phinx documentation](http://docs.phinx.org/en/latest/commands.html#the-status-command) the status command _does_ send a few exit codes but I still lose the details generated by that json format. After an hour of sifting through source code in cake, migrations and phinx I have finally just decided to open an issue about this because it seems silly to offer json formatting but have no way to capture only the json object (this is a problem in Phinx as well but I am not using that package directly).

I would love access to the `ConsoleOutput` object from the `ConsoleIo` object to capture that stream but having the migrations plugin return pure json is a more likely outcome. Sorry if I have missed an obvious solution to this - I really did look for something.

**Comment by HavokInspiration** [comment]
So if I understand correctly, you want only the json output without all the noise around it.
By noise, I mean this : 

```
Welcome to CakePHP v3.2.11 Console
---------------------------------------------------------------
App : src
Path: /home/sdustinh/github/app/src/
PHP : 7.0.8-3+deb.sury.org~trusty+1
```

And so on.

You just want 

```php [{"status":"down","id":"20160525182515","name":"Users"}]```

to be returned, correct ?

**Comment by sdustinh** [comment]
Basically, yeah. The problem I have with it is I can't utilize the json output because of the other stuff. I tried to capture it and filter on my own but there was no easy way to handle it that I could see.

**Comment by berarma** [comment]
I think the "quiet" option should be what you need, but it suppresses ALL output, instead of just the messages.

If you're on Linux this workaround may work supposing the json output is always the last line in the output:
`bin/cake migrations status -f json | tail -n 1`

Or you could suppress the first lines that you don't want if they're always in the same number:
`bin/cake migrations statuys -f json | tail -n +12`

**Comment by dereuromark** [comment]
This should be solved with https://github.com/cakephp/phinx/pull/1600 then?
