### ISSUE TITLE
More comprehensive diff logic

### ISSUE THREAD

**Issue by ifunk** [cakephp/migrations#251]
I am excited to see the diff logic make the list of functionality in this plugin, however there are few features I would love to see.
- Maintain column ordering
- Support for rename detection (columns and tables)

Is there any intention on developing this plugin further to cover those areas?

I have a few ideas on how rename detection could be done non-interactively, but you could also fallback to the interactive console to give the user control.

**Comment by dereuromark** [comment]
How would column ordering work without loosing any date (in those columns)?
How does rename detection work when you add a field and delete another one and those are of a similar type? I think the false positives here are too likely and make this risky.

**Comment by ifunk** [comment]
Column ordering can be done using the `after` option. eg. http://docs.phinx.org/en/latest/migrations.html#valid-column-options

The problem with using `after` is since it's based on column names, you could hit a conflict if a co-worker hasn't pushed their migrations before you create yours (and rename or delete the field that your migration is referencing). But in many cases this might be OK, as long as the developer is aware of this.

With rename detection, one idea I had was using the `comment` option to store a UUID for the table and column and compare on these. Obviously this is a crude way to track changes and not everyone would be keen on this, but it could work. Alternatively, giving the option back to the user is also a solid approach.

**Comment by lorenzo** [comment]
> Support for rename detection (columns and tables)

This is technically impossible, or at least so difficult that is close to impossible.

**Comment by ifunk** [comment]
> This is technically impossible, or at least so difficult that is close to impossible.

@lorenzo After there any factors that I'm not considering? If we could identify the table/column via the comment attribute, this could be fairly straightforward.

**Comment by lorenzo** [comment]
Using the comments is a clever idea, but not acceptable to many. For example, I do use comments all the time for explaining what a table or column is, and I would not want that comment to be altered or replaced with something I did not put there.

Another problem is people manually copying tables form SQL to another table. I do that often as well. By doing this I would accidentally duplicate the comments form the other table, making it impossible to know which table was the original one.

**Comment by ifunk** [comment]
@lorenzo I still this can be achieved, and make it opt-in, but I get your points. The main purpose for opening this ticket was to see if it was on the roadmap (which is now evident that it's not).

What about field ordering? Is this a problem for anyone currently?

**Comment by HavokInspiration** [comment]
Field ordering has been implements in PR #276 and released with version 1.6.5.

As for rename detection, in my opinion, using the comment column seems complicated as well. I have yet to think of a way to do it in a clean way.
