### ISSUE TITLE
Should the file "schema-dump-default.lock" be committed in a Git repo?

### ISSUE THREAD

**Issue by TatzyXY** [cakephp/migrations#252]
Hello,

I have a short question should the "schema-dump-XY.lock" file be committed in a git repo? 
Like a composer.lock file?

I think it makes sense if it will be committed cause then CakePHP can compare the .lock file with the current database but I am really not sure if it is working like this, as I think.

@lorenzo @josegonzalez @HavokInspiration

**Comment by lorenzo** [comment]
Yes, it should be committed

**Comment by ionas** [comment]
In there is some serialized form of the schema as far as I remember. What's the point of that?

**Comment by dereuromark** [comment]
@lorenzo I am not so sure about it being commited.
Or we need to find a way for the server to not modify it (--no-lock ?), because as of now every migration gets you a modified file on server:

    modified:   config/Migrations/schema-dump-default.lock

And a git pull will then abort because of the conflicts here.

**Comment by HavokInspiration** [comment]
I opened PR #284 to add an option that allows devs to skip the dump creation when deploying to avoid conflict if the dump file is commited. The option is available with the `migrate` and `rollback` migrations command as well as when baking a snapshot.
