### ISSUE TITLE
Not correctly handling migrations for schemas other than public with PostgreSQL

### ISSUE THREAD

**Issue by theraccoonbear** [cakephp/migrations#254]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.2.12
* Migrations plugin version: 0.4.3
* Bake plugin version (if relevant): (this pertains to `migrations` not `bake`, as far as I know, and I'm unsure how to find the bake plugin version)
* Database server (MySQL, SQLite, Postgres): PostgreSQL 9.3.11 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit
* PHP Version: PHP Version 5.5.9-1ubuntu4.17
* Platform / OS: Ubuntu 14.04.4 LTS

### What you did
I am unable to run `cake migrations migrate` successfully.  From what I can tell, this issue has to do with the migration connection not querying the correct schema.

My `config/app.php` defines my database connection and includes a `schema` value; a concept found in PostgreSQL, but not other DBs like MySQL.  The actual CakePHP web application works correctly, using data from tables in the specific schema.  When I run the migrations command line tool, I get the following error:

```
[PDOException]                                                                  
SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "phinxlog" does not exist  
LINE 1: SELECT * FROM phinxlog ORDER BY version ASC
```

My guess was that the migration tool was trying to access this `phinxlog` table in the default schema ("public").  Creating the `phinxlog` table in the `public` schema allows me to successfully run the migration.

### Expected Behavior
The migration tool should use a database connection and query builder identical to the web app so users who do not store their application data in the default `public` schema can run migrations successfully.

### Actual Behavior
The migration tool is incorrectly looking for the `phinxlog` table in the default (`public`) schema, instead of where the application configuration specifies.

My concern is that this is possibly a deficiency of the underlying Phinx tool CakePHP is using, but I'm hoping there's a practical solution.

**Comment by theraccoonbear** [comment]
Can anyone else confirm that this problem exists?

**Comment by lorenzo** [comment]
We are apparently passing the schema information to phinx, as seen here:

https://github.com/cakephp/migrations/blob/master/src/ConfigurationTrait.php#L105-L107

Maybe you can debug around those lines and see if there is any problem there?

**Comment by lorenzo** [comment]
And in phinx the schema name is used: https://github.com/robmorgan/phinx/blob/a79b374e1404f7be01fe875cb8b1d2352f74cb09/src/Phinx/Db/Adapter/PostgresAdapter.php#L1166-L1170

**Comment by HavokInspiration** [comment]
Hi.
I tried this locally and I can not reproduce using the last version of the plugin.

Here is my `default` connection config : 

```
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'persistent' => false,
            'host' => 'localhost',
            'username' => 'dev',
            'password' => '*******',
            'database' => 'postgres',
            'schema' => 'dev',
```

I ran a simple migration and it created the `phinxlog` table in the `dev` schema (and left public untouched).
Is there anything we are missing to reproduce what you are experiencing ?

**Comment by theraccoonbear** [comment]
@HavokInspiration I haven't looked at this in a while and am currently on a different project at work, but I'll try to look into this in the next week or so if I can free up some time.

**Comment by HavokInspiration** [comment]
@theraccoonbear When you test that again, can you try using `dev-master` ? I fixed the Postgres test build and what you are experiencing might have been fixed along the way (the test build had issues regarding wrong schema being queried).
