### ISSUE TITLE
Support for MySQL "varbinary" type

### ISSUE THREAD

**Issue by zejji** [cakephp/migrations#255]
This is an:
- [ ] enhancement

Would it be possible to update the Phinx version used by the CakePHP migrations plugin?

In particular, the current master version of Phinx has support for the MySQL **varbinary** type (added by [this](https://github.com/robmorgan/phinx/commit/91dc26921e59275cb5974466bb929aa195780725) commit), which we make extensive use of in our database. Currently, there is no way of adding a varbinary column using the migrations plugin (and the version of Phinx (5.3.1) which it incorporates).

Thanks!

**Comment by HavokInspiration** [comment]
phinx version has been upgraded to 0.6.5 (which included support for the `varbinary` type) as of migrations 1.6.6.
