### ISSUE TITLE
Migrating to Phinx 6.x

### ISSUE THREAD

**Issue by hiromi2424** [cakephp/migrations#257]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)

Is there any plan to use phinx 6.x?
Currently phinx version is fixed as 5.3 in this plugin.
Phinx 6.x has more power of table/column settings, e.g. encoding and collations.
If no features added to this plugin, It is appreciated to place phinx 6.x.

**Comment by elboletaire** [comment]
:+1:

I've ended up here due to a crash in my migrations. I was trying to use `renameTable` which seems to be new in phinx 0.6.X

**Comment by lorenzo** [comment]
I think the only thing preventing the migration is time. Maybe you would like to help?

**Comment by elboletaire** [comment]
I'm sorry Lorenzo but if there's something I do not have is time x_D

I've an issue opened and I can open another related to nested errors, but if I've done nothing of that is due to the time.

Anyway, if I find some time you may find a PR from me.

**Comment by HavokInspiration** [comment]
I opened PR #291 which updates phinx to 0.6.5.
