### ISSUE TITLE
Exceptions are turned into useless error messages

### ISSUE THREAD

**Issue by berarma** [cakephp/migrations#258]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.2
* Migrations plugin version: 8c67ea5e8ed5fd778050652175688aa3593d18c1
* Database server (MySQL, SQLite, Postgres): MySQL 5.5.49
* PHP Version: 5.6.24

This is a request/suggestion to always show a backtrace when an exception gets thrown. The current error message is cute but useless. I don't think it fits in a development/deployment tool.

Although the verbose option already does it, it's inconvenient because it also displays all the queries when query logging is enabled. I often debug my migrations with query logging on but I prefer to read them from a file rather than on the console.

Also, when a migration fails without verbosity on, I have to retry the migration turning verbosity on (and maybe turning query logging off), but retrying migrations isn't always easy when the database doesn't support transactional schema changes. Thus this request to always show the full exception info.

Thanks.

**Comment by lorenzo** [comment]
Do you mind posting a screenshot of how it looks like when you activate the verbose flag vs without it?

**Comment by berarma** [comment]
Here's an example:
http://pasteboard.co/hdS8feAi4.png

**Comment by lorenzo** [comment]
Ok, I see what you mean now. It looks like we will have to report this to phinx or see how it can be worked around

**Comment by berarma** [comment]
I think the problem might be in this plugin. While debugging my problem I saw the Exception was being catched by the Symfony\Component\Console\Application object. It has an option to catch all the exceptions thrown by the underlying code that seems to be on by default.

**Comment by lorenzo** [comment]
@berarma ok, if you find where in this plugin the problem might be it would be of great help!

**Comment by berarma** [comment]
I've submitted a PR.
