### ISSUE TITLE
cake bake migration_snapshot should exclude phinxlog tables

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#267]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: latest
* Migrations plugin version: latest

### What you did

    cake bake migration_diff Foo

### Expected Behavior
Nothing should have changed.

### Actual Behavior

    $this->table('geo_phinxlog', ...

has been added to the migration file, which is the phinxlog table of the geo plugin, unrelated to the actual database content of the app itself.
I think it should skip any `*_phinxlog` table when looking into the diff.

Ideally it would also skip all tables generated and maintained by that other plugin phinxlog, but that will probably be out of scope here.

**Comment by HavokInspiration** [comment]
#263 seems to have fixed this.
