### ISSUE TITLE
Is there possible to migrate many to many

### ISSUE THREAD

**Issue by markstory** [cakephp/migrations#277]
_From @levend18 on November 23, 2016 11:33_

This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

I'm trying to use bin\cake bake migration CreateIsShowInstitutions user._ids:integer Institution._ids:integer
But this is not working.
Is this possible to work with like that. when i do that. This command create 2 tables automaticly and  works fine.

_Copied from original issue: cakephp/cakephp#9789_

**Comment by markstory** [comment]
I don't think migrations supports the behavior you're trying to achieve. You would have to create all 3 tables individually right now.

**Comment by HavokInspiration** [comment]
This is currently not possible and would require some work on the script that is parsing the fields list.

**Comment by dereuromark** [comment]
Stale
