### ISSUE TITLE
All string, text columns are exported as diff by migration_diff

### ISSUE THREAD

**Issue by dala00** [cakephp/migrations#283]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.9
* Migrations plugin version: 1.6.3
* Database server (MySQL, SQLite, Postgres): 10.1.10-MariaDB
* PHP Version: 5.6.19
* Platform / OS: Windows 7 Enterprise

### What you did
Excuted this command without diff.
```
bin/cake bake migration_diff CheckDiffTest
```

### Expected Behavior
Baked migration file has empty up, down function.

### Actual Behavior
All string, text columns became diff.
like
```
$this->table('users')
    ->changeColumn('email', 'string')
    ->changeColumn('authcode', 'string')
    ->update();
```

I don't know why now but this commit may affects.
https://github.com/cakephp/migrations/commit/bbdcbe1ac08044f1578c79ce12bd07591a092612
I deleted this row, migration_diff result became right.
By this commit, result of next condition may changed.
```
$column !== $oldColumn
```

**Comment by dala00** [comment]
I thought that $changedAttributes should be used for condition.

**Comment by HavokInspiration** [comment]
Yes, this is a known bug for 1.6.4.
PR #279 has been opened to take care of this problem, but I will close it in favor of another approach to fix it soon.

**Comment by dala00** [comment]
Oh, I see. thank you.
