### ISSUE TITLE
[Enhancement] Set any column that ends with `_at` to `datetime` default type 

### ISSUE THREAD

**Issue by flashios09** [cakephp/migrations#286]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

If we don't specify the type for the `created`, `modified`, `updated` it will be `datetime`:
> Fields named created and modified will automatically be set to the type datetime.

I think that using the `_at` suffix is more descriptive for datetime columns, `created_at`, `modified_at`, `deleted_at` ... instead of `created` ...

What about adding another condition to check that the column name ends with `_at` and set it automatically to datetime :)

vendor/cakephp/migrations/src/Util/ColumnParser.php :
```php
public function getType($field, $type)
{
    $reflector = new ReflectionClass('Phinx\Db\Adapter\AdapterInterface');
    $collection = new Collection($reflector->getConstants());

    $validTypes = $collection->filter(function ($value, $constant) {
        return substr($constant, 0, strlen('PHINX_TYPE_')) === 'PHINX_TYPE_';
    })->toArray();

    $fieldType = $type;
    if ($type === null || !in_array($type, $validTypes)) {
        if ($type === 'primary') {
            $fieldType = 'integer';
        } elseif ($field === 'id') {
            $fieldType = 'integer';
        } elseif (in_array($field, ['created', 'modified', 'updated']) || substr($field, -3) == '_at') {
            $fieldType = 'datetime';
        } else {
            $fieldType = 'string';
        }
    }

    return $fieldType;
}
```

**Comment by josegonzalez** [comment]
I would say we do both. I know at work we use `created_at` etc., but it's not a CakePHP app. However, that is a common pattern in other frameworks.

One thing you'd need to note is that by default, I don't think Bake supports these alternate names either, so you'd have to deal with adding the TimestampBehavior manually.

**Comment by flashios09** [comment]
@josegonzalez i know that the default are `created` and `modified` for the timestamp behavior so if i choose to use `created_at` and `modified_at` i have to update the config for each table manually(or extend the timestamp behavior)
i tried this `...  bake CreateTests created_at modified_at` and it works(default type to `datetime`) after changing this:
```php
} elseif (in_array($field, ['created', 'modified', 'updated'])) {
```
to this:
```php
} elseif (in_array($field, ['created', 'modified', 'updated']) || substr($field, -3) == '_at') {
```

**Comment by HavokInspiration** [comment]
I agree. This `_at` pattern in common enough to have it included in the plugin.

**Comment by flashios09** [comment]
@HavokInspiration I will create a PR now for this too

**Comment by HavokInspiration** [comment]
PR #292 opened.
