### ISSUE TITLE
 SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' 

### ISSUE THREAD

**Issue by johannesnagl** [cakephp/migrations#30]
I have a mysql 5.6 database with some bigint fields (also for storing internal ids). when baking my default schema (with php cake.php bake migration Initial -c default)

the following code is created:

```
    $table = $this->table('groups');
    $table
      ->addColumn('id', 'biginteger', [
        'limit' => '20', 
        'null' => '', 
        'default' => '', 
      ])
      ...
```

when running the migration with php cake.php migrations migrate the migration throws an error:

```
 SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' 
```

bake is trying to create a "id" field on his own, although phinx has already created the primary "id" key on it's own. 

so i guess, bake should therefore call `$this->table('groups', ['id' => false])`

**Comment by jmacedo** [comment]
I like the auto id feature. I only think that it should create it as unsigned. Because of this, I have to set auto id to false and create all id columns in all tables (we use this like an internal database pattern) .
