### ISSUE TITLE
bake migration_diff is broken for decimal field

### ISSUE THREAD

**Issue by hiromi2424** [cakephp/migrations#310]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.3
* Migrations plugin version: 0.6.5
* Bake plugin version (if relevant): 1.3.1
* Database server (MySQL, SQLite, Postgres): MySQL 5.7.17-0ubuntu0.16.04.1
* PHP Version: 7.1.2-3+deb.sury.org~xenial+1
* Platform / OS: Ubuntu 16.04.2 LTS

### What you did
* modify `lng decimal(14, 10)` field with mysql InnoDB schema
* `bin/cake bake migration_diff Updates`

### Expected Behavior

Diff will contain:

```php
            ->changeColumn('lng', 'decimal', [
                'default' => null,
                'precision' => 14,
                'scale' => 10,
                'null' => false,
            ])
```

### Actual Behavior

```php
            ->changeColumn('lng', 'decimal', [
                'default' => null,
                'limit' => 14,
                'null' => false,
            ])
```

The older version(sorry to forgot, but it might use phinx 0.4.*) can generate precision and scale correctly.
I had not investigated deeply. Perhaps the reason is some of phinx attributes was ignored.

Please anyone catch the thing and get fixed. I manually re-wrote migrations but some other users will encounter this issue.

**Comment by dereuromark** [comment]
I have similar issues with float and length(10,6) - trying to use the precision and scale options.
We should also clarify this more in the docs IMO.

**Comment by HavokInspiration** [comment]
I think I stumbled upon this bug a while back and created a fix : https://github.com/cakephp/migrations/pull/295/files

However no release were done since I went silent which would explain why you are having this bug. I'll have to see if everything is working properly before doing a release. It might take some time though, I'm just getting back in the game.

**Comment by HavokInspiration** [comment]
This should be fixed as a new release has been made.
