### ISSUE TITLE
Phinx is very out of date

### ISSUE THREAD

**Issue by sdustinh** [cakephp/migrations#316]
Is there any intention to keep this plugin up to date with phinx releases? I went to use the `truncate()` method as defined in the phinx documentation and quickly found that it wasn't added until [0.7.1](https://github.com/robmorgan/phinx/releases/tag/v0.7.1) and that the current release is actually 0.8.0.

If the goal is to not keep phinx up to date are there any plans to make this plugin no longer rely on a third-party library for migrations? I would personally love to see this plugin ditch the use of phinx in favor of a pure cake integration.

**Comment by josegonzalez** [comment]
@sdustinh we've thought about not pinning to specific phinx releases (or using a minimum version) but sadly they often break BC so there are fixes necessary to our plugin to ensure it continues to work properly.

Long-term, it's possible that we refactor this to not use phinx, but instead have something that implements as much of the phinx api as possible (so as not to break bc too much for developers).

If you'd like to help out by:

- testing an upgrade to 0.8.0
- refactoring to remove phinx as a dependency

That would be *excellent*.

**Comment by lilHermit** [comment]
Can we expect this to change now that phinx is a CakePHP project?

**Comment by josegonzalez** [comment]
@lilHermit We are currently working on figuring out what the roadmap is for Phinx, though will hopefully be announcing something in this area soon :)

**Comment by ravage84** [comment]
@sdustinh I tried to upgrade it, see here https://github.com/cakephp/migrations/pull/307

**Comment by sdustinh** [comment]
@ravage84 I saw. If only it were so simple. :frowning_face: 

I'd really love to see Cake ditch Phinx all together and roll a migration package that leverages the framework and integrates like a plugin. If the obstacle is PRs, I'm happy to contribute to get us out of phinx.

**Comment by lorenzo** [comment]
@sdustinh actually we have adopted phinx as a cakephp project. So expect a better integration in the future

**Comment by ravage84** [comment]
@sdustinh https://github.com/cakephp/phinx/pull/1119 😼
