### ISSUE TITLE
PHP Warning: fwrite(): 49 is not a valid stream resource

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#327]
With latest migrations release I always get
```
PHP Warning:  fwrite(): 49 is not a valid stream resource in /var/www/.../site/upgrade/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 253
Warning: fwrite(): 49 is not a valid stream resource in /var/www/.../site/upgrade/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 253
PHP Warning:  fwrite(): 93 is not a valid stream resource in /var/www/.../site/upgrade/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 253
Warning: fwrite(): 93 is not a valid stream resource in /var/www/.../site/upgrade/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 253
```
on top when an exception like this happens:
```
Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'email' in [/var/www/.../site/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 338]
```

**Comment by reloxx13** [comment]
same here
windows 10
xamp v3.2.2
PHP 7.1.4 (cli) (built: Apr 11 2017 20:08:12) ( ZTS MSVC14 (Visual C++ 2015) x86 )

**Comment by ravage84** [comment]
Verified, just happend to me after a `Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' `` exception thrown.
Windows 7, PHP 7.1 with MySQL

**Comment by dereuromark** [comment]
It might be a side-effect of the new PSR7 ServerRequest and immutable implementation in core.

**Comment by E-P1983** [comment]
Can confirm, happens to me too.

**Comment by dereuromark** [comment]
Do we still face this, or does the latest version solve it? I didnt see it in my code anymore.

**Comment by ravage84** [comment]
@dereuromark I'm not sure to be honest but what I can recall from recent migrations is that it is way too verbose when it has errors (not in a helpful way) than I like it.

**Comment by dereuromark** [comment]
I think it is resolved.
