### ISSUE TITLE
Non set keys should not be altered

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#330]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Currently

```php
		$table->changeColumn('status', 'string', [
			'encoding' => 'utf8mb4',
			'collation' => 'utf8mb4_unicode_ci',
		]);
```

Kills all other settings like 
```php
			'null' => true,
			'default' => null,
```

One always needs to check and add all those into every changeColumn, instead of just altering what is defined here in the migration file.
This leads to some really dangerous DB regressions.

**Comment by inoas** [comment]
Huh that's unexpected. Sorry. Is there a way to merge?

**Comment by HavokInspiration** [comment]
That's on phinx level if I'm not mistaken... From what I remember, those keys are always set when baking a diff for that very reason.

**Comment by dereuromark** [comment]
Yeah but many do not alter the DB directly and "bake" it, but they write a migration file and want to make sure only those keys are altered.
But that way is completely broken this way :/
Any ideas here, like merging with current schema in the background?

**Comment by HavokInspiration** [comment]
I'm not saying everybody should use a diff, I'm just putting some context around this.

The queries are built and executed by phinx.
To me, this is more of a ticket for phinx rather than the migrations plugin.

**Comment by dereuromark** [comment]
True, but we could in some way shim it by merging before passing it on to phinx, this would keep the BC there and allow our migration generation in CakePHP to make less accidental regressions.

**Comment by HavokInspiration** [comment]
Why doing the work twice ?

phinx should be fixed and the migrations plugin upgraded then to support the new version of phinx.
