### ISSUE TITLE
Upgrade to phinx 0.9+

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#333]
Any reason we cannot upgrade to v0.9.x ( https://github.com/cakephp/phinx/releases ) ?
Currently everyone is stuck with 0.8.1.

This latest minor release contains also vital bugfixes (besides the enhancements).

**Comment by broberts-mrmc** [comment]
Yes, I would also like to see the CakePHP Migrations plugin include Phinx 0.9.1+

Among the item in the subsequent releases, this enhancement in particular would be useful:
https://github.com/robmorgan/phinx/pull/1070

Change log:
https://github.com/cakephp/phinx/blob/c1d51fd065af3aa3fabd684ce561cd9c38281eb8/CHANGELOG.md

**Comment by styks1987** [comment]
I am also interested in seeing this updated

**Comment by lorenzo** [comment]
This was done already
