### ISSUE TITLE
markMigrated() throws exception "You need to pass a ConfigInterface object for your first getManager() call"

### ISSUE THREAD

**Issue by kevinmuller** [cakephp/migrations#334]
Hello.
I am not sure if this is a bug, or maybe a misuse of the function, so I'd like to have your opinion.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.5
* Migrations plugin version: 1.7.1
* Bake plugin version (if relevant): EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Database server (MySQL, SQLite, Postgres): MySQL 5.7.17
* PHP Version: 7.1.9
* Platform / OS: Alpine 

### What you did
Here is a voluntarily simplified example scenario (files created manually):
https://gist.github.com/kevinmuller/62bfc622f1f3064c9de49041058a49a0

Then I run the command: bin/cake migrations migrate

### Expected Behavior
I would expect markMigrated() to execute normally and not throw an exception.

### Actual Behavior
I get the following result:
```bash-4.3$ bin/cake migrations migrate
using migration paths
 - /var/www/project/config/Migrations
using seed paths
 - /var/www/project/config/Seeds
using environment default
using adapter mysql
using database test

== 20171114083933 MigrateTest: migrating
Exception: You need to pass a ConfigInterface object for your first getManager() call in [/var/www/project/vendor/cakephp/migrations/src/Migrations.php, line 332]
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in /var/www/project/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 253

Warning: fwrite(): supplied resource is not a valid stream resource in /var/www/project/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 253
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in /var/www/project/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 253

Warning: fwrite(): supplied resource is not a valid stream resource in /var/www/project/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 253
```
### How I prevent this to happen
In the function markMigrated(), adding $this->getConfig() as a parameter to $this->getManager() seems to fix the problem. See the diff below:
```bash-4.3$ diff ./vendor/cakephp/migrations/src/Migrations.php ./vendor/cakephp/migrations/src/MigrationsFixed.php
--- ./vendor/cakephp/migrations/src/Migrations.php
+++ ./vendor/cakephp/migrations/src/MigrationsFixed.php
@@ -234,7 +234,7 @@
         $migrationPaths = $this->getConfig()->getMigrationPaths();
         $params = [
             array_pop($migrationPaths),
-            $this->getManager()->getVersionsToMark($input),
+            $this->getManager($this->getConfig())->getVersionsToMark($input),
             $this->output
         ];
```
If you confirm that it's a bug, I'd be happy to do a Pull Request if necessary!

Many thanks.

**Comment by dereuromark** [comment]
not an issue anymore afaik
