### ISSUE TITLE
CakePHP Migrations Plug-In Incorrectly Reports Phinx Version

### ISSUE THREAD

**Issue by broberts-mrmc** [cakephp/migrations#335]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.5
* Migrations plugin version: 1.7.1
* Database server (MySQL, SQLite, Postgres): MariaDB 
* PHP Version: ~5.6
* Platform / OS: Window 7, Windows Server 2008, Windows Server 2012

### What you did
```
> composer show -i

.
.
.
cakephp/bake                        1.4.4              Bake plugin for CakePHP 3
cakephp/cakephp                     3.5.5              The CakePHP framework
cakephp/chronos                     1.1.2              A simple API extension for DateTime.
cakephp/debug_kit                   3.11.1             CakePHP Debug Kit
cakephp/migrations                  1.7.1              Database Migration plugin for CakePHP 3.0 based on Phinx
.
.
.
robmorgan/phinx                     v0.8.1             Phinx makes it ridiculously easy to manage the database migrations for your PHP app.
.
.
.

> cake

Welcome to CakePHP v3.5.5 Console
---------------------------------------------------------------
App : src
Path: C:\src\
PHP : 5.6.27
---------------------------------------------------------------
.
.
.

> phinx -V
Phinx by Rob Morgan - https://phinx.org. 0.8.1

> cake migrations -V
Migrations plugin, based on Phinx by Rob Morgan. 0.4.3
```

### Expected Behavior
Output correct version string for installed Phinx release as follows:
```
> phinx -V
Phinx by Rob Morgan - https://phinx.org. 0.8.1

> cake migrations -V
Migrations plugin, based on Phinx by Rob Morgan. 0.8.1
```

### Actual Behavior
Outputs incorrect version string for installed Phinx release as follows:
```
> phinx -V
Phinx by Rob Morgan - https://phinx.org. 0.8.1

> cake migrations -V
Migrations plugin, based on Phinx by Rob Morgan. 0.4.3
```

The `initialize()` method of the `MigrationsShell` class appears to be responsible for determining the installed Phinx release version but, if the `PHINX_VERSION` constant does NOT already exists, appears only to use PHP's built-in `STRPOS` function on two string literals.   Ostensibly, the result of the `STRPOS` function is ALWAYS `true`, which returns static version string "0.4.3" assigning it to constant `PHINX_VERSION`.  This does not appear to do anything meaningful, at least not as it relates to ascertaining the actual version string for the installed Phinx release.

https://github.com/cakephp/migrations/blob/master/src/Shell/MigrationsShell.php#L88
https://github.com/cakephp/migrations/blob/32871746b1ddab4c0b4d7b33f02a871dc9d1e141/src/Shell/MigrationsShell.php#L88

**Comment by dereuromark** [comment]
Are you able to provide a fix as PR?

**Comment by broberts-mrmc** [comment]
Seems there‘s a dependent/prerequisite PR for Phinx that’s open and waiting to be merged: https://github.com/cakephp/phinx/pull/1263

I’d like to see that dispositioned by the project managers first. Assuming it will be merged, the solution I propose here would be either:

A. Read the YAML version file created in https://github.com/cakephp/phinx/pull/1263

B. Identify and invoke existing Phinx method, if any, that returns Phinx version string to Cake migrations plugin or create a method (new PR for Phinx project) if one does not exist

Before coding a solution and submitting the PR, I’d like feedback on whether either or both of these proposed solutions would be acceptable solutions?

Solution “B” would potentially involve PRs for both projects.
