### ISSUE TITLE
migration_diff not detecting  unique key

### ISSUE THREAD

**Issue by jaynarayan89** [cakephp/migrations#338]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.4
* Migrations plugin version: 0.4.3.
* Bake plugin version (if relevant): 3.5.4
* Database server (MySQL, SQLite, Postgres): MySQL
* PHP Version: 7.1.10
* Platform / OS: windows7

### What you did
I have changed my database to add a composite unique key using phpmyadmin.  After that, I  used migration_diff command to bake migration for this change.

*  migration file was created with the bake tool 
* command I typed :  bin/cake bake migration_diff CreateUniqueConstraintInUsersTable

### Expected Behavior
code to add a unique key to the table should be generated

### Actual Behavior
code to add a unique key to the table not generated

**Comment by odan** [comment]
I have the same problem.

CakePHP Version: 3.6
Migrations plugin version: 2.0.0
Database server: MySQL
PHP Version: 7.2
Platform / OS: Windows 7

After adding a new unique key, the migration class is empty:

```php
public function up()
{
}

public function down()
{
}
```
