### ISSUE TITLE
'unique' attribute ignored in MigrationHelper::attributes()

### ISSUE THREAD

**Issue by PhantomWatson** [cakephp/migrations#339]
This is a:
* [x] bug

* Migrations plugin version: 1.7.1

`MigrationHelper::attributes()` goes to the trouble of making sure that the 'unique' attribute is boolean, but doesn't include it in `$validOptions`, which results in it being ignored. It appears that either 'unique' should be added to `$validOptions` or removed from the `switch` block.

**Comment by dereuromark** [comment]
Are you able to provide a fix as PR? That would be awesome!
