### ISSUE TITLE
Dump command executed in different shell

### ISSUE THREAD

**Issue by dorxy** [cakephp/migrations#353]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.12 #a6c47f15e2dfbb062fcc547d6eecd0a944dc8b17
* Migrations plugin version: 1.7.2 #a5612adfd2efa8c90d29cb3b0c969de872a99eda
* Database server (MySQL, SQLite, Postgres): MariaDB - 10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04
* PHP Version: 7.0.27
* Platform / OS: Mac OS 10.13.3

### What you did
I created my own migration shell, unrelated to phinx migrations, which can be run using the `bin/cake migrations` command. It can also be used with its plugin prefix, `bin/cake plugin.migrations`.
Whenever I wish to run phinx migrations, I must run `bin/cake migrations.migrations migrate` which is fine. The problem arises however when the migrations shell wishes to create its dump.
In the code, MigrationsShell::115, we can clearly see that dispatching the shell is done using the `migrations dump` command, without plugin prefix.

### Expected Behavior
I expect the migrations shell to take into account the original command given with regard to the plugin prefix of the command name.

### Actual Behavior
The plugin calls my own migrations plugin with the dump task, which should never happen!

### Efforts
I have tried to resolve this but it is clear in Cake/Console/CommandRunner::137 the original name of the command is simply stripped from the arguments, making it impossible to determine how the shell was called initially. Perhaps some extra parameter could be a resolution, but I figured the contributors might find the best solution for this.

**Comment by dereuromark** [comment]
Is this still an issue with commands?
