### ISSUE TITLE
migration_snapshot generates invalid column types (tinyint)

### ISSUE THREAD

**Issue by harpax** [cakephp/migrations#355]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.13
* Migrations plugin version: 1.7.2
* Bake plugin version (if relevant): 1.6.3.
* Database server (MySQL, SQLite, Postgres): Percona 5.7
* PHP Version: 7.0.9
* Platform / OS: Win7

### What you did
Creating an initial dump from an existing database using
`bin/cake bake migration_snapshot initial`

### Expected Behavior
A working snapshot file, that can be migrated as it is

### Actual Behavior
The snapshot could not be migrated. I am using tinyints in the schema, that were exported as such

    ->addColumn('sort', 'tinyinteger', [
                'default' => '1',
                'limit' => 3,
                'null' => false,
                'signed' => false,
            ])

I found that phinx does not support variants of ints other than biginteger and the boolean type which creates a tinyint. It would be nice if phinx could support that

**Comment by MarwanSalim** [comment]
i also face the same problem

**Comment by GitHubMouhssine** [comment]
Adding field type of boolean adds tinyint column of length 1
$table
      ->addColumn('sort', 'boolean', [
                'default' => false,
                'null' => false,
            ]);

**Comment by karmicdice** [comment]
What is the column length you specified?

**Comment by markstory** [comment]
@GitHubMouhssine MySQL Doesn't have a boolean type. Instead it uses `TINYINT(1)` as its boolean type.

**Comment by dereuromark** [comment]
Anyone wanting to make a PR?

**Comment by karmicdice** [comment]
> Anyone wanting to make a PR?

But where is the bug? Tinyint is used as boolean type because mysql does not have a boolean. Instead we use int?

**Comment by dereuromark** [comment]
> But where is the bug? Tinyint is used as boolean type because mysql does not have a boolean. Instead we use int?

bool is tinyint(1)
tinyint(2), sth like enum is not boolean, thus we still need to support tinyint for length 2 or 3.

**Comment by karmicdice** [comment]
Oh Yes! Makes sense... In essence, the system as it stands has made tinyint as the de-facto for boolean, whereas tinyint obviously has more than 1 use case.

**Comment by dereuromark** [comment]
No, tinyint(1) is boolean as any other use case can be done with tinyint(2). There is no need to do anything else here with tinyint(1). Everything on top would be wrong nano optimization beyond any usefulness.

**Comment by karmicdice** [comment]
Yes, we are on the same page.
It is like..

if ( len(tinyint-column) > 1):
   produce tinyint
else:
   produce boolean

? Is this what we are looking at? So as long as it is tinyint 1- we leave it as it is...

**Comment by karmicdice** [comment]
Unable to run migrations with Cake 4. Are we targeting this feature for 3.8x?

**Comment by karmicdice** [comment]
There is already a check in place : https://github.com/cakephp/cakephp/blob/4.x/src/Database/Schema/MysqlSchema.php#L106:L108

Let me try to replicate this in 3.8x

**Comment by saeideng** [comment]
>Unable to run migrations with Cake 4.

are you sure ?

**Comment by karmicdice** [comment]
> > Unable to run migrations with Cake 4.
> 
> are you sure ?
> you can use latest commit on branch 4.x

Oh branch 4.x. Yes!!! Let me check....

**Comment by karmicdice** [comment]
> > Unable to run migrations with Cake 4.
> 
> are you sure ?
> you can use latest commit on branch 4.x

Unable to fork 4.x

**Comment by saeideng** [comment]
```
    "require": {
        "php": ">=7.2",
        "cakephp/cakephp": "4.x-dev",
        "cakephp/plugin-installer": "^1.0",
        "mobiledetect/mobiledetectlib": "2.*"
    },
    "require-dev": {
        "cakephp/bake": "4.x-dev",
        "cakephp/cakephp-codesniffer": "dev-next",
        "cakephp/debug_kit": "4.x-dev",
        "cakephp/migrations": "4.x-dev",
        "josegonzalez/dotenv": "3.*",
        "phpunit/phpunit": "^8.0",
        "psy/psysh": "@stable"
    },
```

and then `composer update`

**Comment by karmicdice** [comment]
Yea, I get that.. but to send a PR, I need to be able to fork it, no?

**Comment by saeideng** [comment]
fork all repo and then use symlink if you use linux (and if you want to test in an app ) 
you can fork all repo and then witch to needed branch

**Comment by markstory** [comment]
If you have an existing fork that doesn't have the 4.x branch you can do:

```bash
git remote add cakephp git://github.com/cakephp/migrations
git fetch cakephp
```

After that you should be able to checkout the 4.x branch.

**Comment by MathRat** [comment]
Hi,

same problem here.
CakePHP 3.8

I created an inital snapshot with this snippet in it.
`->addColumn('anzahl', 'tinyinteger', [
                'default' => null,
                'limit' => 3,
                'null' => false,
                'signed' => false,
            ])`

i tried to rename db, created a new one and to migrate to this.

> InvalidArgumentException: An invalid column type "tinyinteger" was specified for column "anzahl". in C:\wamp64\www\timo\vendor\rob
morgan\phinx\src\Phinx\Db\Table.php:305

i got an initial migration that i can't re-migrate. Is the only solution to reconfigure all fields with type tinyint?

**Comment by markstory** [comment]
> i got an initial migration that i can't re-migrate. Is the only solution to reconfigure all fields with type tinyint?

Yes, or contribute a fix and use the fixed generators to rebuild your initial migration.

**Comment by dereuromark** [comment]
`'tinyinteger'` for length 2/3 is still not supported at this point.

**Comment by dereuromark** [comment]
See
- https://github.com/cakephp/migrations/pull/457
- https://github.com/cakephp/phinx/pull/1755

I was able to confirm with Mysql already in a real app. Works like a charm.

**Comment by mehov** [comment]
Hi everyone, 

I ran into the same issue, found this on Google, but still unsure how to proceed. The linked issues didn't clarify this either.

> InvalidArgumentException: An invalid column type "tinyinteger" was specified for column "duration". 

I'm using CakePHP 3.8. The problematic migration code is.

```
->addColumn('duration', 'tinyinteger', [
    'default' => null,
    'limit' => 3,
    'null' => true,
    'signed' => false,
])
```

(Tried replacing `tinyinteger` with `tinyint` but that didn't help.)

I have been following CakePHP database naming conventions and instead of everything working seamlessly this is what I get. 

- What do I have to do when creating migrations to prevent this in the future?
- I'm okay with editing the migrations file, but please document - or at least give me an idea how exactly should I edit it.
