### ISSUE TITLE
Char columns are migration diffed as Varchar

### ISSUE THREAD

**Issue by markstory** [cakephp/migrations#362]
_From @dmromanov on May 13, 2018 18:0_

* CakePHP Version: 3.6.2
* Migrations plugin version: 1.8.1
* Bake plugin version: 1.7.3
* Database server (MySQL, SQLite, Postgres): MySQL 5.7, 8.0
* PHP Version: PHP 7.2.3
* Platform / OS: Ubuntu 18.04

We have the following DB.
```MySQL
CREATE TABLE `test` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `iso6392` char(2) NOT NULL COMMENT 'Country code, ISO 639-2'
);
```
After running `bin/cake bake migration_diff Init` Init I get:

```php
<?php
use Migrations\AbstractMigration;

class Init extends AbstractMigration
{
    public function up()
    {

        $this->table('test')
            ->addColumn('iso6392', 'string', [
                'comment' => 'Country code, ISO 639-2',
                'default' => null,
                'limit' => 2,
                'null' => false,
            ])
            ->create();
    }

    public function down()
    {
        $this->dropTable('test');
    }
}
```
No mention of "Char" column type. Applying this migration on another DB will result `iso6392` column having a `varchar` column type instead of expected `char` type.
This might be critical if this column will be used as a foreign key - migration will fail.

In addition, a column comment is lost when baking a migration_diff to change a column from varchar to char type.

_Copied from original issue: cakephp/bake#446_

**Comment by markstory** [comment]
The migration bake task comes from the migration plugin.

**Comment by Kimita** [comment]
```
        $this->table('test')
            ->addColumn('iso6392', \Phinx\Db\Adapter\MysqlAdapter::PHINX_TYPE_CHAR, [
                'comment' => 'Country code, ISO 639-2',
                'default' => null,
                'limit' => 2,
                'null' => false,
            ])
            ->create();
```
Is this not a workaround?

**Comment by karmicdice** [comment]
The workaround is good but it can be more aesthetic.

It should have defaulted to char.

I reckon, something is up at https://github.com/cakephp/migrations/blob/master/src/Util/ColumnParser.php#L193-L198

**Comment by karmicdice** [comment]
Please transfer this to Cakephp/Cakephp
Referencing a PR for this.
