### ISSUE TITLE
Phinx version

### ISSUE THREAD

**Issue by EdouardTack** [cakephp/migrations#364]
This is a :
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.4
* Migrations plugin version: 1.8.1
* Bake plugin version : 1.8
* Database server (MySQL, SQLite, Postgres): 5.7.14 - MySQL
* PHP Version: 7

### What i would like

Can we update phinx version for migrations plugin [composer line](https://github.com/cakephp/migrations/blob/master/composer.json#L22) ? Or why we can't ?
I need the last version of phinx, but i can't. [Issue on phinx repo](https://github.com/cakephp/phinx/issues/1362#issuecomment-395406736)

**Comment by dereuromark** [comment]
Dup of https://github.com/cakephp/migrations/issues/333
