### ISSUE TITLE
Implement twig templates

### ISSUE THREAD

**Issue by danger2k7** [cakephp/migrations#366]
This is a (multiple allowed):
* [] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6.0.
* Migrations plugin version: 2.0.0.
* Bake plugin version (if relevant): 1.8.0.

I could not find an issue to pass from .ctp to .twig templates, seeing that Bake uses now twig as default template engine, is there an project to do this ?

**Comment by dereuromark** [comment]
Not yet, but it would sure be a nice addition to 3.x, and also 4.x then.
Feel free to make a PR here.

**Comment by dereuromark** [comment]
PR welcome for upcoming 4.x release.

**Comment by dereuromark** [comment]
Is this still relevant?
