### ISSUE TITLE
Can a single migration be run within a plugin?

### ISSUE THREAD

**Issue by medero** [cakephp/migrations#368]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.9
* Migrations plugin version: 1.8.0
* Bake plugin version (if relevant): 1.0
* Database server (MySQL, SQLite, Postgres): MySQL
* PHP Version: 7.1
* Platform / OS: Ubuntu 16.04

I created a migration file for an existing table to add a new column.

```
<?php
use Migrations\AbstractMigration;

class AddFileToOrders extends AbstractMigration
{
    /** 
     * Change Method.
     *
     * More information on this method is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-change-method
     * @return void
     */
    public function change()
    {   
        $table = $this->table('orders');
        $table->addColumn('file_id', 'integer', [
            'default' => null,
            'limit' => 11, 
            'null' => false,
            'signed' => false,
        ]); 
        $table->update();
    }   
}
```

Which exists in plugins/Orders/config/Migrations as 20180727155114_AddFileToOrders.php

And I wanted to run this migration, specifically. So I ran:

```
bin/cake migrations migrate -t 20180727155114 -p Orders
```

### Expected Behavior
I expected just this migration file to run, within the plugin

### Actual Behavior
It runs everything inside of plugin/Orders/config/Migrations.

Is there a way to have this run the specific file within the plugin?

**Comment by lorenzo** [comment]
Would you like to help implementing this?

**Comment by swiffer** [comment]
Is it possible that other command Line switches Like --no-lock do Not Work either?

**Comment by dereuromark** [comment]
A PR to enable this would be welcome.

**Comment by MayMeow** [comment]
I found this issue but. maybe what i write is here is wrong so dont blame me.

But you dont need to run all migrations till target one? (and this is implemented or no?). Migration like this above will add field to table so lets say i dont have created this table but want run specific migration like that... it will return missing table error.
