### ISSUE TITLE
Flags are not passed to Phinx adapter

### ISSUE THREAD

**Issue by nickygerritsen** [cakephp/migrations#374]
This is a
* [x] bug

* CakePHP Version: 3.5.11 (but also newer versions)
* Migrations plugin version: 
* Bake plugin version (if relevant): 1.7.2 (but also newer versions)
* Database server (MySQL, SQLite, Postgres): MariaDB 10.3.10-MariaDB-1:10.3.10+maria~bionic-log (but doesn't matter)
* PHP Version: 7.0.28-0ubuntu0.16.04.1 (but doesn't matter)
* Platform / OS: Ubuntu 16.04 (but doesn't matter)

### What you did
If you have a datasource as below example:
```php
        'default' => [
            'className'        => 'Cake\Database\Connection',
            'driver'           => 'Cake\Database\Driver\Mysql',
            'persistent'       => false,
            'host'             => 'hostname',
            'port'             => '3306',
            'username'         => 'username',
            'password'         => 'password',
            'database'         => 'database',
            'encoding'         => 'utf8',
            'timezone'         => 'UTC',
            'ssl_key'          => '/home/test/client-key.pem',
            'ssl_cert'         => '/home/test/client-cert.pem',
            'ssl_ca'           => '/home/test/ca-cert.pem',
            'flags'            => [PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false]
```

The `flags` do not get passed to the Phinx adapter.
If these flags are required to connect to the server (like the SSL_VERIFY_SERVER_CERT one is for us), connecting failed, because of this line: https://github.com/cakephp/migrations/blob/master/src/CakeAdapter.php#L56
It tries to connect but fails.

I think the flags should be passed somewhere around here: https://github.com/cakephp/migrations/blob/master/src/ConfigurationTrait.php#L127

### Expected Behavior
Migration works by passing the flags through to the underling adapter.

### Actual Behavior
Migration fails with a MariaDB `2002` error because PDO tries to verify the server cert CN name, which does not match.

**Comment by swiffer** [comment]
Same for timezone Parameter (breaking Data Migration for timestamp Columns). the Adapter is Not in Line with CakePHP core package.

**Comment by dereuromark** [comment]
PR welcome.
