### ISSUE TITLE
4.x ctp twig templates to true twig ext

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#386]
are those dead templates?
https://github.com/cakephp/migrations/tree/master/src/Template/Bake

now that bake uses twig for templating?

**Comment by garas** [comment]
They are Twig templates with .ctp extensions.

**Comment by dereuromark** [comment]
I didnt expect that.. All right then.

**Comment by dereuromark** [comment]
Given the fact that Cake4 moves from ctp to php extension.
Can we rename those then to true twig extension?

**Comment by garas** [comment]
I would agree. I had additional task to configure my IDE to use .ctp as Twig during my last PR to this repo

**Comment by dereuromark** [comment]
IDEs would then automatically understand also the type here, yeah.
But also it is more clear when looking at the file names iteself.

**Comment by saeideng** [comment]
done in 4.x branch
