### ISSUE TITLE
Ability to add decimal value while using bake

### ISSUE THREAD

**Issue by karmicdice** [cakephp/migrations#388]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8
* Platform and Target: Apache2, Ubuntu 18.04

### What you did
`bin/cake bake migration AddAmountToInvoices amount:decimal[10,3]`

### What happened
It should add a decimal column with 10,3

### What you expected to happen
It created a String with 255

### What I propose...
There should be an ability to bake decimal columns while defining their _thing_

If I am shown the right direction, I can perhaps add this ability to bake and submit a PR. ?

**Comment by karmicdice** [comment]
I am half way through coding a major change. Thought I will ask if it will be welcome.
Just as how to we 'created' and 'modified' auto change to datetime. I am trying to make latitude and longitude create float(10,6)
Ofcourse the ideal solution is [Spatial database](https://dev.mysql.com/doc/refman/8.0/en/spatial-types.html) but the market share for websites is heavily relying on Google maps so I would like to go with what [Google maps recommends](https://developers.google.com/maps/solutions/store-locator/clothing-store-locator?csw=1#creating-a-table-in-mysql).

What do you guys think?

**Comment by markstory** [comment]
I think inferring types for `latitude` and `longitude` column names is reasonable if the user can still override the inference with their own types.

**Comment by karmicdice** [comment]
> if the user can still override the inference with their own types.

Are you advising that if user wants to have `latitude` or `longitude` as varchar they should still be able to do so?

At the moment in get `getType`

    elseif (in_array($field, ['latitude', 'longitude']) {
                $fieldType = 'float';
            } else {

I have added the above.

It [already has a null check at 201.](https://github.com/cakephp/migrations/blob/master/src/Util/ColumnParser.php#L200-L201) So we are good on that area.

**Comment by karmicdice** [comment]
Have sent a PR.
If alls good, will update the docs to accomodate decimal.
