### ISSUE TITLE
CHAR type is not available with Phinx

### ISSUE THREAD

**Issue by Bridn** [cakephp/migrations#4]
Phinx is not able to create a CHAR(36) type column.

For example this migration creates a primary key as VARCHAR(36) type field, this is not supported as UUID key :

```
$terms = $this->table('terms', array('id' => false, 'primary_key' => array('id')));
$terms->addColumn('id', 'string', array('limit' => 36))
->save();
```

I have to manually change it.

[Phinx doc - valid-column-types](http://phinx.readthedocs.org/en/latest/migrations.html#valid-column-types)

**Comment by nhiennn** [comment]
Please help, I can not set uuid type limit that always return char(36) ???

**Comment by HavokInspiration** [comment]
@nhiennn What db server are you using ?

**Comment by nhiennn** [comment]
In phinx I used "uuid" type to create "char" type in database:
->addColumn('text','uuid',['limit' => 4, 'null' => true])
but after migrate, in datatable struct is text  char(36). I can not set limit for this type to char(4) ???

**Comment by HavokInspiration** [comment]
Well, UUID is a special type of column that have a fix length of 36.
You might want to try to use ``->addColumn('text', 'char', ['limit' => 4, 'null' => true])``
