### ISSUE TITLE
Feature: Seed order

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#405]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement

### status quo
Currently you can either run them specifically or all at once.
You cannot, however, specify the order.

### Allow setting order
For visual display of available seeds but also more importantly when running them all, there should be the possibility to define orders, or at least some priorities.

I added seeds for roles and for users, but the users (having role_id) can only work if the roles already exist, especially with some constraints on DB level in place.

What are thoughts on this?

**Comment by ccatterina** [comment]
Hi,
Am I wrong or this feature is already available using `getDependencies` function?

https://github.com/cakephp/phinx/pull/1244

**Comment by mehov** [comment]
This shows up in search results. Here's n example on how to actually use `getDependencies()`: https://github.com/cakephp/phinx/blob/a96c5465a8f3dd64e39c9115a5d383b8d01928ce/tests/Phinx/Migration/_files/seeds/PostSeeder.php
