### ISSUE TITLE
Can't create tinyint field in sql server

### ISSUE THREAD

**Issue by mcsknp** [cakephp/migrations#406]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8
* Migrations plugin version: 2.0
* Bake plugin version (if relevant): 1.9
* Database server (MySQL, SQLite, Postgres): SQL Server 2017
* PHP Version: 7.2
* Platform / OS: Windows 10

In Mysql I can use limit to set field type to tinyint but there is no way to do it in Sql Server.

**Comment by dereuromark** [comment]
Does tinyint(1) for boolean fields work? Or is that including all enum - tinyint(2/3) - an issue?

**Comment by mcsknp** [comment]
Tinyint(1) for boolean is worked.

**Comment by dereuromark** [comment]
You should just be using `boolean` as type the Engine itself should find the right internal type here.

And that is supported:

        case static::PHINX_TYPE_BOOLEAN:
                return ['name' => 'bit'];
