### ISSUE TITLE
The phpstan-shim will not be updated anymore

### ISSUE THREAD

**Issue by odan** [cakephp/migrations#416]
> With PHPStan 0.12, phpstan-shim is no longer needed and will not be updated anymore. All users should move to phpstan/phpstan. PHPStan extensions continue to work as expected.

Source: https://medium.com/@ondrejmirtes/phpstan-0-12-released-f1a88036535d

https://github.com/cakephp/migrations/blob/master/composer.json#L59

* Migrations plugin version: 2.4.1

Github provides a link to the latest phpstan phar file.

The url is: https://github.com/phpstan/phpstan-shim/raw/master/phpstan.phar

**Example for a fix version:**

```json
"phpstan-setup": "php -r \"@mkdir('build'); copy('https://github.com/phpstan/phpstan/releases/download/0.11.19/phpstan.phar', 'build/phpstan.phar');\"",
"phpstan": "php build/phpstan.phar analyse src --level=max --no-progress",
```

**Comment by dereuromark** [comment]
Yes, we know :)
feel free to make a PR here, but bear in mind that 0.12 has still a lot of bugs and most likely cannot yet migrated to.

**Comment by dereuromark** [comment]
PR open
