### ISSUE TITLE
Plugin migration unknown short option 'p'

### ISSUE THREAD

**Issue by kaliel86** [cakephp/migrations#417]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0
* Migrations plugin version: 3.0.0-beta1
* Bake plugin version (if relevant): 4.0
* Database server (MySQL, SQLite, Postgres): MariaDB 10.4.10-2
* PHP Version: 7.4
* Platform / OS: 5.4.2-arch1-1

### What you did
Made a fresh install of cake 4.0 then i created a plugin with only one migration in it, then
`bin/cake migrations migrate -p MyPluginName`

### Actual Behavior
The migration did what was expected, but a this message was printed in console output
`All Done. Took 0.0063s
Error: Unknown short option p.
`

**Comment by saeideng** [comment]
A PR now is open
thanks for reporting
