### ISSUE TITLE
Installation request for cakephp/migrations

### ISSUE THREAD

**Issue by harikt** [cakephp/migrations#422]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: NZ
* Migrations plugin version: `3.*@beta`
* Bake plugin version (if relevant): NA
* Database server (MySQL, SQLite, Postgres): NA
* PHP Version: 7.3.9
* Platform / OS: Ubuntu : 18.04

### What you did

```json
{
    "require": {
	"cakephp/migrations": "3.*"
    },
    "minimum-stability": "beta"
}
```

### Expected Behavior

Install 3.x beta version

### Actual Behavior

Problem 1
    - cakephp/migrations 3.0.0-beta2 requires robmorgan/phinx 0.next-dev -> satisfiable by robmorgan/phinx[dev-0.next] but these conflict with your requirements or minimum-stability.
    - cakephp/migrations 3.0.0-beta1 requires robmorgan/phinx 0.11.x-dev -> no matching package found.
    - Installation request for cakephp/migrations 3.* -> satisfiable by cakephp/migrations[3.0.0-beta1, 3.0.0-beta2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

It may be nice to remember the dependencies is also in beta state rather than in dev version.

If we change minimum-stability to dev, then this will work as expected. But cakephp/migrations is in beta.

**Comment by ADmad** [comment]
You need to use `"minimum-stability": "dev"` for the time being until as phinx doesn't have a beta tagged yet.

**Comment by harikt** [comment]
Yes. That is what I meant. If the dependencies is not tagged beta, then there is no use of releasing beta.

**Comment by harikt** [comment]
For those who are struggling to install beta, can use something like this for the current time. So remaining packages installed will be stable. Alternatively can use --prefer-stable flag I believe.

```
"cakephp/migrations": "3.*@beta",
"robmorgan/phinx": "dev-0.next"
```
