### ISSUE TITLE
migrations migrate command should return a non-zero exit code on error

### ISSUE THREAD

**Issue by fholznagel** [cakephp/migrations#426]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.8
* Migrations plugin version: 2.4.1
* Bake plugin version (if relevant): not relevant
* Database server (MySQL, SQLite, Postgres): not relevant
* PHP Version: 7.2.26
* Platform / OS: centos 6.10

### What you did
I am calling _bin/cake migrations migrate_ from within the deployer tool (https://deployer.org/). If one of the migrations produce an error/throw an exception the overall migration process is correctly cancelled. But the CakePHP migrate command doesn't return a non-zero exit code in this situation. Thus, the calling process is not informed about the error.

I tried to track down the cause of the problem and found the following:

Phinx\Migration\Manager\Environment::executeMigration() throws an exception.
The exception is caught in Phinx\Console\Command\Migrate::execute() and results in returning self::CODE_ERROR.
Migrations\Command\CommandTrait::execute() ignores the return value from Migrate::execute() and returns void.
Migrations\Command\Migrate::execute() returns BaseCommand::CODE_SUCCESS.

### Expected Behavior
bin/cake migrations migrate should return a non-zero exit code on a migration error.

### Actual Behavior
bin/cake migrations migrate returns the exit code 0 on a migration error.

I found a comparable issue in #215 but it applies to a rather old version of the migrations plugin.

**Comment by saeideng** [comment]
yes because command classes dont use result of `CommandTrait::execute()`
partially fixed `void` in https://github.com/cakephp/migrations/pull/413 
but needs to use/check `CommandTrait::execute()` result

would you like to open a PR?

**Comment by fholznagel** [comment]
> would you like to open a PR?
Will try to do so, but it may take a few days.

**Comment by dereuromark** [comment]
since this is a rather critical issue I looked into it right away - can you check https://github.com/cakephp/migrations/pull/431 please?

**Comment by fholznagel** [comment]
Thanks so much!
