### ISSUE TITLE
[2.0.0-2.0.4] Bake migration_snapshot throws exception when trying to mark migrated

### ISSUE THREAD

**Issue by challgren** [cakephp/migrations#428]
So I created a new app following the instructions on cakephp/app and when baking my first migration using the `bin/cake bake migration_snapshot Initial` the following exception is generated. However the migration file is generated but the phinx tables are not generated and the migration is not marked as applied. I'm not sure if this should be reported in cakephp/cakephp or cakephp/migrations or here. However if I do `bin/cake migrations mark_migrated` the phinx table is generated and the migration is mark as migrated. I know @wrdx on Slack was also experiencing this issue.

When I first created my original 4.x app I was able to successfully bake a migration and it be run. That migration is dated 20191222 so I'm not sure if something changed in the past month that would be causing this new error.

```
Mac-mini:bequest challgren$ bin/cake bake migration_snapshot Initial

Creating file /Users/challgren/Projects/bequest/config/Migrations/20200126121547_Initial.php
Wrote `/Users/challgren/Projects/bequest/config/Migrations/20200126121547_Initial.php`
Marking the migration 20200126121547_Initial as migrated...
Exception: Shell class for "Migrations" could not be found. If you are trying to use a plugin shell, that was loaded via $this->addPlugin(), you may need to update bin/cake.php to match https://github.com/cakephp/app/tree/master/bin/cake.php
In [/Users/challgren/Projects/bequest/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 332]
```

**Comment by saeideng** [comment]
I transferred the issue to correct place

and I wanna convert this shell/task (mark_migrated) to command soon

**Comment by Ali1** [comment]
Also the schema lock is not being updated which causes problems for further migration_diff generation.

**Comment by Ali1** [comment]
As a workaround modify SnapshotTrait.php and replace 2 lines around like 66 with
```php
        $this->_io->out('Marking the migration ' . $fileName . ' as migrated...');
        debug($dispatchCommand);
        //$this->dispatchShell($dispatchCommand);
```
And around line 87 with:
```

        $this->_io->out('Creating a dump of the new database state...');
        debug($dispatchCommand);
        //$this->dispatchShell($dispatchCommand);
```

This will give you two commands to run manually (bin/cake .....) to achieve normal behavior

**Comment by dereuromark** [comment]
PR welcome if this is still an issue.

**Comment by dereuromark** [comment]
This is fixed in Cake5 right?

**Comment by challgren** [comment]
> This is fixed in Cake5 right?

I think it's fixed in all recent versions
