### ISSUE TITLE
Migrations command forces Bake to be require instead of require-dev

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#433]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

```
PHP Fatal error:  Class 'Bake\Command\SimpleBakeCommand' not found in /var/www/dereuromark/sandbox4/vendor/cakephp/migrations/src/Command/BakeSeedCommand.php on line 31
Fatal Error: Class 'Bake\Command\SimpleBakeCommand' not found
In [/var/www/dereuromark/sandbox4/vendor/cakephp/migrations/src/Command/BakeSeedCommand.php, line 31]
```

### What you did
Deploy using "cakephp/bake" as recommended require-dev plugin.

### Expected Behavior
No exceptions.

### Actual Behavior
Blows up with fatal error, probably due to commands being "loaded" in CLI.

**Comment by saeideng** [comment]
even in migration 2 ( cake 3 ) there is line 
```php
use Bake\Shell\Task\SimpleBakeTask;
```
and in composer.json 
```
    "require-dev": {
        "cakephp/bake": "....",
    },
```
looks you dont load the bake in your composer.json so we can and maybe should move it to `require` section !! ?

**Comment by dereuromark** [comment]
We need to, but we shouldnt need to :)
Before it wasnt an issue as the commands/shells werent inspected on bin/cake load, now they are - which causes this negative side effect.

**Comment by saeideng** [comment]
shells(bake type)  are not in help list but commands (bake type) are 
why shells have not problem? I dont know 

a solution for command would be : 
we can exclude bake classes with override the `console` hook 
```php
    public function console(CommandCollection $commands): CommandCollection
    {
        $commands = $commands->discoverPlugin($this->getName());
        //remove  bake from `$commands` and add the  remains 
        return $commands->addMany( $commands);
    }
```

probably it will work , I can try it :)

**Comment by markstory** [comment]
@saeideng I solved a similar problem in authorization by checking for bake and conditionally adding commands that depended on bake only if it was present.

**Comment by saeideng** [comment]
I tried, the problem was in `spl_autoload_register()` and composer

if you use
```php
            try {
                $reflection = new ReflectionClass($class);
            } catch (ReflectionException $e) {
                continue;
            }
```
in bake plugin or 
```php
            if (
                !is_subclass_of($class, Shell::class)
                && !is_subclass_of($class, CommandInterface::class)
            ) {
                continue;
            }
```
in `CommandRunner` to exclude classes 
you receive 
```php
PHP Fatal error:  Class 'Bake\Command\SimpleBakeCommand' not found in ....src/Command/BakeSeedCommand.php on line ....
```
because it tries  to include `Bake`'s class in 
```php
//vendor/composer/ClassLoader.php
function includeFile($file)
{
    include $file;
}
```
and `ReflectionClass` class could not cover it

**Comment by saeideng** [comment]
just there is one solution finding and adding shells/command manually or creating a custom `commandScanner`

**Comment by dereuromark** [comment]
PR open: https://github.com/cakephp/migrations/pull/456
