### ISSUE TITLE
unsigned not a vaild column

### ISSUE THREAD

**Issue by pjosephson** [cakephp/migrations#44]
"unsigned" is not a valid value for use with the table.  You must use "signed" => false/true with phinx

**Comment by markstory** [comment]
I am pretty sure this was fixed. Have you tried updating to the most recent commits?

**Comment by dereuromark** [comment]
I wonder what that https://github.com/cakephp/migrations/tree/migration-generation branch is, but it is 29 commits ahead of master.

**Comment by markstory** [comment]
@dereuromark You're right I'm thinking of the changes in #34 which @josegonzalez is sitting on.

**Comment by josegonzalez** [comment]
Sorry, I'll finish off my pr this weekend :)

**Comment by simkimsia** [comment]
following because I have the same issue as well

**Comment by josegonzalez** [comment]
This is fixed in master now. Closing.
