### ISSUE TITLE
id automatically created forcing column already exists.

### ISSUE THREAD

**Issue by pjosephson** [cakephp/migrations#45]
As you can tell I have been playing with the Migrations plugin today.  Phinx by default creates an id as the primary unless overridden in the table function. 
For example: $this->table('users', ['id' => false, 'primary_key' => ['user_id']]);

The current cake bake migration command will make an id column in the migration file causing an 'Column already exists' when using the migration file  because the id is being defined twice in the process.

**Comment by dakota** [comment]
I believe this has been addressed with previous PRs, including #55
