### ISSUE TITLE
Update robmorgan/phinx

### ISSUE THREAD

**Issue by daniel-lang** [cakephp/migrations#49]
I tried to update the phinx versionof this plugin with composer  but it stays at 0.3.5 (current version is 0.4.1). I found the version in the MigrationsShell:49
(`define('PHINX_VERSION', (0 === strpos('@PHINX_VERSION@', '@PHINX_VERSION')) ? '0.3.5' : '@PHINX_VERSION@');`)

Is there a easy way to update the plugin?

**Comment by markstory** [comment]
The [composer dependency]() is tracking `dev-master`. https://github.com/cakephp/migrations/blob/master/composer.json#L26. To update the printed version a pull request will be sufficient.
