### ISSUE TITLE
The bake migration snapshot command does not include the index names in the migration snapshot.

### ISSUE THREAD

**Issue by kgbph** [cakephp/migrations#491]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.6.
* Migrations plugin version: 3.1.0.
* Bake plugin version (if relevant): 2.5.1.
* Database server (MySQL, SQLite, Postgres): MySQL 5.6
* PHP Version: PHP 7.4
* Platform / OS: Debian

### What you did
I executed `bin/cake bake migration_snapshot Initial` against a database with named indexes.

### Expected Behavior
The index names are present in the generated migration snapshot.

### Actual Behavior
The index names were not present in the generated migration snapshot, although the indexes were present.

**Comment by dereuromark** [comment]
PR open
But we do need to have CI working again before we can continue.
