### ISSUE TITLE
migrate command need not try to create Seeds directory.

### ISSUE THREAD

**Issue by nishimura-d** [cakephp/migrations#511]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 4.2.9
* Migrations plugin version: 3.1.0
* PHP Version: 8.0.5
* Platform / OS: Linux

### What you did

1. Add a plugin with migrations and without seeds (eg. `dereuromark/cakephp-queue`)
2. Deploy to the environment where `vendor` directory is owned by root and not writable by others.
3. Run the migrations by non-root user. `bin/cake migrations migrate --no-lock -p Queue`

### Expected Behavior

No warnings occur.

### Actual Behavior

```
2021-09-27 18:14:51 Warning: Warning (2): mkdir(): Permission denied in [/var/www/html/vendor/cakephp/migrations/src/ConfigurationTrait.php, line 86]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 188
mkdir - [internal], line ??
Migrations\Command\Phinx\Migrate::getConfig() - ROOT/vendor/cakephp/migrations/src/ConfigurationTrait.php, line 86
Phinx\Console\Command\AbstractCommand::bootstrap() - ROOT/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php, line 107
Migrations\Command\Phinx\Migrate::bootstrap() - ROOT/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php, line 66
Phinx\Console\Command\Migrate::execute() - ROOT/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php, line 63
Migrations\Command\Phinx\Migrate::parentExecute() - ROOT/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php, line 37
Migrations\Command\Phinx\Migrate::execute() - ROOT/vendor/cakephp/migrations/src/Command/Phinx/Migrate.php, line 85
Symfony\Component\Console\Command\Command::run() - ROOT/vendor/symfony/console/Command/Command.php, line 255
Symfony\Component\Console\Application::doRunCommand() - ROOT/vendor/symfony/console/Application.php, line 992
Symfony\Component\Console\Application::doRun() - ROOT/vendor/symfony/console/Application.php, line 255
Symfony\Component\Console\Application::run() - ROOT/vendor/symfony/console/Application.php, line 148
Migrations\Command\MigrationsCommand::execute() - ROOT/vendor/cakephp/migrations/src/Command/MigrationsCommand.php, line 126
Cake\Console\BaseCommand::run() - CORE/src/Console/BaseCommand.php, line 179
Migrations\Command\MigrationsCommand::run() - ROOT/vendor/cakephp/migrations/src/Command/MigrationsCommand.php, line 198
Cake\Console\CommandRunner::runCommand() - CORE/src/Console/CommandRunner.php, line 336
Cake\Console\CommandRunner::run() - CORE/src/Console/CommandRunner.php, line 172
[main] - ROOT/bin/cake.php, line 12

using migration paths 
 - /var/www/html/vendor/dereuromark/cakephp-queue/config/Migrations
using seed paths 
using environment default
using adapter mysql
using database demo_cms
ordering by creation time

All Done. Took 0.0284s
```

### My opinion

It is enough that Seeds directory is created when a Seed file is created.

https://book.cakephp.org/phinx/0/en/seeding.html

> Database seeding is entirely optional, and Phinx does not create a seeds directory by default.

**Comment by dereuromark** [comment]
> Warning: Warning (2): mkdir(): Permission denied

What path is it trying to access? What file is it trying to write?

**Comment by nishimura-d** [comment]
> What path is it trying to access? What file is it trying to write?

`/var/www/html/vendor/dereuromark/cakephp-queue/config/Seeds`

mkdir before deploy supresses the warning, but I don't want to do that.

**Comment by dereuromark** [comment]
--no-lock should not modify any files
So what file is it trying to write?

**Comment by nishimura-d** [comment]
I added `--no-lock` not to write under `config/Migrations`.
Regardless of the option, the command try to mkdir `config/Seeds` if the directory does not exist.
https://github.com/cakephp/migrations/blob/8ce8de77c4c2c7f61a74ef672431228262cab3c9/src/ConfigurationTrait.php#L85-L86

In my deployment, `config` directory is not writable by the application user.
