### ISSUE TITLE
TestSuite\Migrator fails on PostgreSQL with PostGIS

### ISSUE THREAD

**Issue by vmikhav** [cakephp/migrations#526]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.3.0
* Migrations plugin version: 3.3.0
* Database server (MySQL, SQLite, Postgres): PostgreSQL 14.1, PostGIS 3.1
* PHP Version: 8.0
* Platform / OS: Ubuntu 20.04

### What you did
Test database has PostGIS plugin. This plugin creates table `spatial_ref_sys` and views `geography_columns` and `geometry_columns`.
`\Migrations\TestSuite\Migrator` is trying to drop all tables and rerun migrations. There is two issues:
- `ConnectionManager::get($connection)->getSchemaCollection()->listTables()` doesn't filter by type and gets tables and views. `\Cake\TestSuite\ConnectionHelper::dropTables` cannot drop view and fails. `\Cake\TestSuite\ConnectionHelper::truncateTables` will fail too.
- Table and views, created by plugin, shouldn't be deleted.

### Expected Behavior
Migrator shouldn't fail on the bootstrap stage.

### Actual Behavior
Migrator fails, issues are describen above.

**Comment by othercorey** [comment]
@markstory This looks like another issue with dropping everything from `listTables()`.

**Comment by markstory** [comment]
> This plugin creates table spatial_ref_sys and views geography_columns and geometry_columns.
\Migrations\TestSuite\Migrator is trying to drop all tables and rerun migrations. There is two issues:

Are these tables created via migrations? How do the tables get created?

**Comment by vmikhav** [comment]
> Are these tables created via migrations? How do the tables get created?

These tables are created by PostGIS (when you do `CREATE EXTENSION postgis;`) and they cannot be dropped or truncated.

**Comment by markstory** [comment]
Related to cakephp/cakephp#16123

**Comment by vmikhav** [comment]
I extended `Migrator` and made a workaround that is similar to the following code:
```php
class Migrator
{
    protected array $protectedTables = [];

    public function setProtectedTables(array $tables): void
    {
        $this->protectedTables = $tables;
    }
...
    protected function getNonPhinxTables(string $connection): array
    {
        $tables = ConnectionManager::get($connection)->getSchemaCollection()->listTables();

        return array_filter($tables, function ($table) {
            return strpos($table, 'phinxlog') === false && !in_array($table, $this->$protectedTables);
        });
    }
}
```
