### ISSUE TITLE
Baked Drop* migration does not drop the table actually.

### ISSUE THREAD

**Issue by nishimura-d** [cakephp/migrations#559]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 4.4.3
* Migrations plugin version: 3.5.2
* Bake plugin version (if relevant): 2.7.1
* Database server (MySQL, SQLite, Postgres): MySQL
* PHP Version: 8.1.6
* Platform / OS: Linux

### What you did

schema:

```sql
create table examples
        (
            id int auto_increment,
            constraint examples_pk
                primary key (id)
        )
```

shell commands:

```
$ bin/cake bake migration DropExamples

Creating file /var/www/html/config/Migrations/20220727033411_DropExamples.php
Wrote `/var/www/html/config/Migrations/20220727033411_DropExamples.php`
$ bin/cake migrations migrate
using migration paths 
 - /var/www/html/config/Migrations
using seed paths 
 - /var/www/html/config/Seeds
using environment default
using adapter mysql
using database my_app
ordering by creation time

 == 20220727033411 DropExamples: migrating
 == 20220727033411 DropExamples: migrated 0.0109s

All Done. Took 0.1130s

Dumps the current schema of the database to be used while baking a diff

using migration paths 
 - /var/www/html/config/Migrations
using seed paths 
 - /var/www/html/config/Seeds
Writing dump file `/var/www/html/config/Migrations/schema-dump-default.lock`...
Dump file `/var/www/html/config/Migrations/schema-dump-default.lock` was successfully written
```

### Expected Behavior

The `examples` table is dropped.

`change` method of baked migration should end with `$table->update();`.

### Actual Behavior

The `examples` table remains.

`change` method of baked `20220727033411_DropExamples.php`:

```php
    public function change()
    {
        $table = $this->table('examples');
        $table->drop();
    }
```

`$table->drop()` merely add an action and do not execute it.

**Comment by dereuromark** [comment]
Check migration or phinx docs:
https://github.com/cakephp/phinx/blob/0.x/docs/en/migrations.rst#dropping-a-table
The save() itself is important to execute.

**Comment by nishimura-d** [comment]
Yes.
`save()` is identical to `update()` when the table exists.
https://book.cakephp.org/phinx/0/en/migrations.html#saving-changes
We never drop a table which does not exist.

Why bake does not output `update()` statement like other migrations?

**Comment by dereuromark** [comment]
Good question, sounds like an oversight
Maybe you want to make a PR here?

**Comment by nishimura-d** [comment]
Sorry I overlooked #553 which is same as this.
It just has not released yet.
