### ISSUE TITLE
ID columns now unsigned by default since 3.7.0

### ISSUE THREAD

**Issue by deanoj** [cakephp/migrations#599]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.3.10.
* Migrations plugin version: 3.7.1
* Bake plugin version (if relevant): EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Database server (MySQL, SQLite, Postgres): mysql  Ver 15.1 Distrib 10.4.20-MariaDB, for Win64 (AMD64)
* PHP Version: 7.4.22
* Platform / OS: Windows 10

### What you did
Prior to migrations v3.7.0 (v3.6.1 for example) - when creating the table, the ID primary column would by default be created as a singed integer type column.
Since v3.7.0, these ID column are now unsigned by default.

This means all my foreign key references will now throw an error, causing all my tests to fail.

I'm not sure if this was intentional, as I can find nothing in the changelog indicating this.

**Comment by ADmad** [comment]
This is an intentional change, please check the updated release notes for 3.7.0 https://github.com/cakephp/migrations/releases/tag/3.7.0

**Comment by deanoj** [comment]
Yes I can see it in the changelog now - I somehow missed that first time round. Thanks.
