### ISSUE TITLE
bake migration_diff does not support --source for multiple database configs

### ISSUE THREAD

**Issue by Rakasch** [cakephp/migrations#608]
This is a (multiple allowed):
* [X] bug
* [X] enhancement
* [X] feature-discussion (RFC)
* [X] missing feature

* CakePHP Version: 4.4.11
* Migrations plugin version: 3.7.2
* Bake plugin version (if relevant): 2.8.3
* PHP Version: 8.1

### What you did
I have a Cake Projekt with two Databases.
Therefore I'm using migrations with two database configs: "default" and "logs".
And I have two folders, first folder for the default db config "Migrations", second folder for the "logs" database config "MigrationsLogs".

Most of the migration commands support a -s or --source option for the migrations to use another folder.
eg. bin/cake migrations dump -c logs -s MigrationsLogs

My issue is, that the bin/cake bake **migration_diff** command does **not** have a -s or --source option.
Therefore I cant use migration_diff on my "logs" database config.

I can define the datasource with -c to use "logs" but it will try to create the migration in the default "migrations" folder an throw an error because the migration status is obviously wrong in the other datasource. it checks with migration status, but without --source the check fails. So --source should set the migrationPath to "MigrationsLogs".

Feels like it's been forgotten to add the -s option to migration_diff.

![image](https://user-images.githubusercontent.com/8471027/226398977-e2b0824a-f64c-4519-a245-26ef5c053d06.png)

### Expected Behavior
migration_diff command should support two Migration Folders.

**Comment by telepathPiddlingAccent** [comment]
Hello @Rakasch,

I implemented this in https://github.com/cakephp/migrations/pull/618
