### ISSUE TITLE
Decouple ConfigurationTrait from the shell?

### ISSUE THREAD

**Issue by burzum** [cakephp/migrations#61]
I'm trying to re-use the migrations plugin inside an installer event so that the user can activate a plugin through a web interface and the app will run the migrations after that.

When I started I figured out that I can't really re-use the ConfigurationTrait because it depends on `$this->input` being available. But this will effectively couple the trait to a shell.

**Comment by josegonzalez** [comment]
You could mock out $this->input?

**Comment by HavokInspiration** [comment]
@burzum Can you confirm that this issue and #37 are asking for the same thing ?

**Comment by burzum** [comment]
@HavokInspiration guess it is, haven't had the time to give it a closer look yet.
