### ISSUE TITLE
Schema not quoted on Postgres

### ISSUE THREAD

**Issue by pabloelcolombiano** [cakephp/migrations#633]
When running on Postgres with a dashed schema (e.g. `my-schema`), the following line will throw an error, as the schema is not being quoted. 

https://github.com/cakephp/migrations/blob/ac1d9566393c29e8c168c427c310f1ec6aad60cf/src/CakeAdapter.php#L62C79-L62C79

**Comment by othercorey** [comment]
Looks like it's an issue in both 3.x and 4.x.

**Comment by othercorey** [comment]
Closed in https://github.com/cakephp/migrations/pull/635
