### ISSUE TITLE
Unexpected behavior after snapshot

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/migrations#65]
I don't really know if it can be considered a bug or not, but I encountered an unexpected behavior while using migrations.

I took over a project that already had a database with tables inside it. Migrations were not used. When I took over I decided to start using migrations.
With the help of bake, I made a snapshot of the current state of the database.
I needed a new column in a table so I baked a migration. So far so good.
I then made the migration and that's where I stumbled upon the unexpected behavior : the call to ``bake migrations migrate`` triggered an error, saying that it could not create the tables since they already exist.  

It was basically trying to migrate the snapshot.
I had to manually add the snapshot version to the ``phinxlog`` table for it to migrate only the changes needed (being the new column in a table).
After that everything went smoothly... As you see, not a bug _per se_. I hesitated reporting this, since it is rather normal that it does that.

Maybe the phinxlog table needs to be updated after a snapshot was baked ?

**Comment by lorenzo** [comment]
I would say this is a bug. Would you like to help us fix it?

**Comment by HavokInspiration** [comment]
Yes, I can give it a try.
Just have to find my way through the internals of the plugin.
I'll ask for help if I get lost.

**Comment by AD7six** [comment]
Phinx doesn't have a command to say "mark this migration applied" - which to me is an omission; you'll need to execute:

    insert into phinxlog values('the id', now(), now());

For phinx to think the newly-created migration has already been applied.

Maybe useful, for more drastic versions of that problem: https://gist.github.com/AD7six/0afcf0f206b13a877fab

**Comment by dereuromark** [comment]
A trick would be to have a conditional check in there and do not run the queries if a table exists that would have been there on the first "init" migration.

**Comment by HavokInspiration** [comment]
Thanks for the tip about phinx @AD7six.
Executing the raw query was actually the thing I had in mind as a last resort.
I guess you bought me some time.

**Comment by AD7six** [comment]
@dereuromark true, but that breaks reversible migration files (i.e. the change method - which a snapshot doesn't use, but should).

**Comment by HavokInspiration** [comment]
I started working on this yesterday night and here is where I'm going.
Before marking the migration as applied, I want to make sure the migration file is correctly written, hence I have to wait for the file creation to be done and successful.
So my idea is to override the ``createFile`` method of the ``MigrationSnapshotTask`` (being a sub-sub-sub[...] class of ``Shell``) and build something like this :

```php
//MigrationSnapshotTask class
public function createFile($path, $contents)
{
	$created = parent::createFile($path, $contents);

	if ($created) {
		$this->_markSnapshotApplied($path)
	}

	return $created;
}

public function _markSnapshotApplied($path)
{
	//Get the version from $path and make the query
	ConnectionManager::get($this->connection)->insert( /* [...] */ );
}
```

This also ensures that the version number is correct and exactly match the one from the file.
The idea is to have the ``_markSnapshotApplied()`` return the status of the query.
Depending on that, we could have the migration file deleted and report the migration baking a failure if the query could not be made.

What do you guys think ? 
The only thing bothering me is to have the ``createFile()`` method do something else than creating a file.
I also explored the Event way, but could not find one that was triggered after the file was successfully created. So marking the snapshot applied before that seems inappropriate to me. 

If this idea seems okay for you, I'll try to implement this.
I will need to find a way to tell phinx to create the table if it does not exist and find a way to get the right table name.

**Comment by HavokInspiration** [comment]
I started on this but I decided to create a ``mark_migrated`` command that I will try to call after the file was saved. 
While cleaner, it might also prove useful to have such a command.
