### ISSUE TITLE
migrations and Phinx causes error with migrations due to INT casting on migration version

### ISSUE THREAD

**Issue by Hazmit** [cakephp/migrations#650]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.4.15
* Migrations plugin version: "cakephp/migrations": "^3.9",
* Bake plugin version (if relevant): 2.9
* Database server (MySQL, SQLite, Postgres):MySQL 5.7.24 - MySQL Community Server (GPL)
* PHP Version: PHP 7.4.1 (cli) (built: Jan 20 2020 22:21:57) ( ZTS Visual C++ 2017 x86 )
* Platform / OS: Windows 10 22H2

### Expected Behavior
Trying to use migrations to make an initial migration from database and then add a new migration to add a column to an existing table.

### Actual Behavior
When you try to migrate it always recognizes the version of the migration to be null integer value (2147483647) it looks like in the phinx code in Util.php line 93 it casts the version from the filename into an (int) which I think doesn't work because the migrations creates a file name longer than what an integer can contain. For that reason I believe it then returns max value of int value every time and so the migrations plugin thinks every migration is the same version then throws errors about duplicate migration versions.

![image](https://github.com/cakephp/migrations/assets/488993/9fb469a1-f5fd-4914-820c-c3e376cc4d0b)

![image](https://github.com/cakephp/migrations/assets/488993/e8e2b946-8575-423e-b8c4-6ea5b0c405c4)

I've tried muddling with the code a little and seeing if I could adjust from casting into an int to using a varchar and changeing the phinxlogs db field from bigint to varchar but it looks like there is a lot of code hitched to this and I don't want to veer off the beaten path with what code is distributed. This might be a known issue but I couldn't find anything out there pointing to it.

**Comment by garas** [comment]
Phinx requires 64 bit version of PHP.
