### ISSUE TITLE
blob column seems broken

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#662]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 5.x

### What you did

Schema for testing:
```
'image' => ['type' => 'blob', 'length' => null, 'null' => true],
```

### Expected Behavior
Should work for sqlite (does), but also for mysql (NO) and postgres (NO).
For the latter it would translate to bytea I assume, for mysql blob should be fine.

### Actual Behavior
```
Error in bootstrap script: PDOException:
SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "DEFAULT"
LINE 5: "image" DEFAULT NULL,
```

Refs https://github.com/dereuromark/cakephp-captcha/actions/runs/6946005086

**Comment by dereuromark** [comment]
I also tried

    'image' => ['type' => 'varbinary'],

Similar/same issue:

> SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","
LINE 5: "image",

**Comment by ajibarra** [comment]
@dereuromark Could you please share your code?

I have tried with a new migration and:

```
$this->table('posts')
            ->addColumn('name', 'string', ['length' => 255])
            ->addColumn('description', 'string', ['length' => 255])
            ->addColumn('image', 'blob', ['length' => null, 'null' => true])
            ->create();
```

and it creates the field correctly. I am probably missing something but if you share your code it's better.

My versions:

```
cakephp/cakephp                                5.0.3   The CakePHP framework
cakephp/migrations                             4.1.1   Database Migration plugin for CakePHP based on Phinx
```

**Comment by dereuromark** [comment]
The code is linked in that failing CI run
You can execute it locally by checking out master (cakephp 5) and see that it only works for SQlite apparently.
Not sure why blob doesnt seem to work for Mysql and Postgres.

**Comment by dereuromark** [comment]
I moved away from it for now.
