### ISSUE TITLE
How to migrate migration files?

### ISSUE THREAD

**Issue by hakito** [cakephp/migrations#674]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: Upgrade to 5.0
* Migrations plugin version: 4.1.1
* PHP Version: 8.2

### What you did
I am currently upgrading to CakePHP 5.0. Therefore I also upgraded the migrations plugin to 4.1.1. But after the upgrade the migratiion files did not work anymore. 

I tried the upgrade tool for the path to the migration files - but it didn't do anything. Is there a documentation on how to migrate the migration files?

**Comment by markstory** [comment]
There shouldn't be much to do with migration files. You may need to add typehints to methods and parameters but I'm not aware of any required upgrades for migrations. If we discover some that could be automated with rector, then I'm happy to make those changes once we better understand what issues are in your way. Do you get any errors or stacktraces when running migrations?

**Comment by LordSimal** [comment]
I don't remember having any major problems with migrations when upgrading from Cake4 to Cake5

**Comment by hakito** [comment]
I had two required changes:

First add the type to `$autoId`

```diff
- public $autoId = false;
+ public bool $autoId = false;
```

Then `getQueryBuilder()` now requires an argument.

```diff
- $database = $this->getQueryBuilder()->getConnection()->config()['database'];
+ $database = $this->getQueryBuilder(Query::TYPE_INSERT)->getConnection()->config()['database'];
```

But this wasn't even documented at the Phinx repository.

**Comment by dereuromark** [comment]
That method only proxies to

            Query::TYPE_SELECT => $this->getCakeConnection()->selectQuery(),
            Query::TYPE_INSERT => $this->getCakeConnection()->insertQuery(),
            Query::TYPE_UPDATE => $this->getCakeConnection()->updateQuery(),
            Query::TYPE_DELETE => $this->getCakeConnection()->deleteQuery(),
            
So I think you rather want to use `getSelectBuilder()` instead directly

**Comment by dereuromark** [comment]
These things could be a rector ruleset for phinx/migrations

**Comment by umer936** [comment]
Just ran into this issue. 

Changed `getQueryBuilder()` to `getUpdateBuilder()` in all cases and it's fixed (all of mine were updates so if you do an insert, delete, whatever, use the appropriate builder).
