### ISSUE TITLE
RFC: [no-phinx] Show warning if table instance has actions attached which haven't been executed

### ISSUE THREAD

**Issue by LordSimal** [cakephp/migrations#696]
* [x] feature-discussion (RFC)

In the heat of development it can easily happen that we forget things. E.g. look at this code:

```
$this->table('project_inquiry_data')->drop();
$this->table('project_inquiries')->drop();
```

it looks like 2 tables will be dropped because why shouldn't they.

Well, nothing actually happens when executing the migration because I didn't call `->save()` or `->update()`

The migration just happily runs through and says its done.

So it should have looked like
```
$this->table('project_inquiry_data')->drop()->save();
$this->table('project_inquiries')->drop()->save();
```

which - just from an API perspective - looks a bit weird to be honest...

---

My proposal:

Throw an exception - or at least show a warning - if actions are present inside table instances which haven't been executed.

**Comment by markstory** [comment]
I like the idea.

> Throw an exception - or at least show a warning - if actions are present inside table instances which haven't been executed.

I think an error is justified here. The developer has made a mistake that we can easily detect in many scenarios so we should alert them of the error.

> which - just from an API perspective - looks a bit weird to be honest...

I agree with you that `drop()` should be a terminal method (like `create()` and `save()` are). I have concerns on how we make that change with an easy upgrade path to avoid a hard breaking change. Perhaps the return of `drop()` could be a null object that emits deprecations?

**Comment by dereuromark** [comment]
Back in the days it was terminal, and then it became the opposite for 3.6+?
It would indeed be better to go back what it was, the deprecation throwing sounds doable without creating too much breaking changes.
