### ISSUE TITLE
Impossible to use with Sqlite adapter when not in memory 

### ISSUE THREAD

**Issue by real34** [cakephp/migrations#7]
It seems to be impossible to run migrations on a Sqlite database not ran in memory because Phinx always adds a suffix to the database path, and Cake doesn't.

Also in this case there are a few undefined indexes

# To reproduce

Create a datasource:
```
'Datasources' => [
	'default' => [
		'className' => 'Cake\Database\Connection',
		'driver' => 'Cake\Database\Driver\Sqlite',
		'database' => ROOT . DS . 'project_management',
	]
]
```

Generate a migration like the following one:

```
 public function change()
    {
        $projectsTable = $this->table('projects');
        $projectsTable->addColumn('name', 'string')
            ->addColumn('created', 'datetime')
            ->create();
    }
```

# What happens

* There are a few undefined indexes such as "login", "host", "password" when running the shell, due to unchecked indexes in https://github.com/cakephp/migrations/blob/f607c9e3bb23462b9bb20c8e970bdfdeca75a952/src/ConfigurationTrait.php#L85 (in the case of Sqlite they are not needed for the datasource)
* Phinx applies migrations to an incorrect database file. In the example, it will write it to `ROOT . DS . 'project_management.sqlite3'` (because of https://github.com/robmorgan/phinx/blob/b71ccb15a32656067508b23aef1dfb726fff4ce3/src/Phinx/Db/Adapter/SQLiteAdapter.php#L72)

# Expected

* No undefined indexes or notices displayed when running the shell
* Migrations must be applied to the file used by the CakePHP app

**Comment by josegonzalez** [comment]
Fixed upstream by https://github.com/robmorgan/phinx/pull/392 :)
