### ISSUE TITLE
RFC: [no-phinx] Check if given plugin actually exists before executing command

### ISSUE THREAD

**Issue by LordSimal** [cakephp/migrations#708]
I just typoed the following command:

```
bin/cake migrations mark_migrated -p CakedC/Users --target=20240328215332 --only
```

and it happily created a `caked_c_users_phinxlog` table with the "correct" entry.

But in fact only 

```
bin/cake migrations mark_migrated -p CakeDC/Users --target=20240328215332 --only
```

should be valid since that's the actual name of the plugin and therefore the skipped migration should have been put into the `cake_d_c_users_phinxlog` table

**Comment by markstory** [comment]
I think this will be fixed by the changes I have in the no-phinx branch. There are already tests for running `migrations migrate` and plugins needing to exist. I've added a test covering `mark_migrated` as well.
