### ISSUE TITLE
Required robmorgan/phinx cannot be loaded

### ISSUE THREAD

**Issue by Tijme** [cakephp/migrations#71]
When running a fresh install of CakePHP3 I get the following error.

[RuntimeException]                                                                                                                                                                  
Could not load package cakephp/migrations in http://packagist.org: [UnexpectedValueException] Could not parse version constraint >=0.4.2 <1.0: Invalid version string "0.4.2 <1.0"

cakephp/migrations requires robmorgan/phinx, but the version string is incorrect (well, at least thats what the error says).

I am running the following command to install CakePHP: composer create-project --prefer-dist cakephp/app portfolio

Screenshot of the error:
![schermafbeelding 2015-04-10 om 20 32 39](https://cloud.githubusercontent.com/assets/5873573/7094355/ca62597a-dfc0-11e4-85a1-687df924f851.png)

**Comment by ceeram** [comment]
run composer self-update to solve this

2015-04-10 20:27 GMT+02:00 Tijme <notifications@github.com>:

**Comment by Tijme** [comment]
Hi @ceeram,

After composer self-update, composer still tells me the package robmorgan/phinx could not be found.

**Full composer message:**
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cakephp/migrations dev-master -> satisfiable by cakephp/migrations[dev-master].
    - cakephp/migrations dev-master requires robmorgan/phinx >=0.4.2 <1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by ceeram** [comment]
@Tijme a fresh install would not require dev-master of migrations:
https://github.com/cakephp/app/blob/master/composer.json#L11

migrations 1.0.2 does indeed require phinx 0.4.2 because of this https://github.com/cakephp/migrations/issues/66

I cannot reproduce the error you get on a fresh install, also demonstrated here: https://github.com/cakephp/migrations/issues/66#issuecomment-91204796

**Comment by Tijme** [comment]
@ceeram I tried dev-master because 1.0 didn't work. I tried 1.0 again today (which was also required with the fresh install), and now it seems to work. Don't know if it's my fault, or just some crazy bug.

Anyway, thanks for the help!
