### ISSUE TITLE
rollback

### ISSUE THREAD

**Issue by tgoeminne** [cakephp/migrations#722]
when you do rollback should the phinxlog entry in db not be deleted?

i do migrate -p plugin then rollback -p plugin, then want to do migrate again not work due to phinxlog entry in db?

**Comment by markstory** [comment]
> when you do rollback should the phinxlog entry in db not be deleted?

Yes, the records in phinxlog should be removed when a migration has been rolled back. There are tests covering this. Knowing more about which commands you're running would help with reproducing this issue.

**Comment by tgoeminne** [comment]
bin/cake migrations migrate -p name, and same with rollback -p name

**Comment by markstory** [comment]
I've added a test case for the situation you've described so far in https://github.com/cakephp/migrations/commit/fab711c6660dcb446e863de9d6c442d01edaa53e what are we missing in order to reproduce this?
