### ISSUE TITLE
bake migration_diff has issues with signed/unsigned primary keys and foreign keys.

### ISSUE THREAD

**Issue by thonhaus** [cakephp/migrations#723]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 5.0.8
* Migrations plugin version: 4.3.1
* Bake plugin version (if relevant): 3.1.1
* Database server (MySQL, SQLite, Postgres): MariaDB 10.3.28
* PHP Version: 8.2.13

### What you did

1. Created the database according to the definition from the tutorial (see https://book.cakephp.org/5/en/tutorials-and-examples/cms/database.html) and set up an empty Cake project based on the skeleton app.
2. Ran `bin/cake bake migration_diff FooBar`
3. Applied ` bin/cake migrations migrate` on an empty database

### Expected Behavior
Everything should work ;-)

### Actual Behavior
The migration fails with errno: 150 "Foreign key constraint is incorrectly formed".

This is because the primary keys are all created without a sign definition and thus are "signed" in the database. However, the migrations always create the (then automatically generated) ID columns as unsigned. Therefore, the foreign keys do not work anymore.

When switching back to CakePHP 4.5.5 / Migrations 3.9.0 everything works fine.

**Comment by markstory** [comment]
When using migrations 4.3.1 were you also using the `builtin` backend? I ask because migrations has both a phinx and non-phinx backend right now.

**Comment by thonhaus** [comment]
Didn't know that the builtin backend isn't default. With the builtin backend everything is working fine.

**Comment by markstory** [comment]
Good to hear that the new backend is working well. That backend will become the default in the next release as the phinx backend is being phased out. Going to close as the new backend doesn't exhibit this problem and it will become the default soon.
