### ISSUE TITLE
new adapter type returned for PostgreSQL with new built-in backend

### ISSUE THREAD

**Issue by LordSimal** [cakephp/migrations#747]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 5.1.0
* Migrations plugin version: 4.4.0
* Database server (MySQL, SQLite, Postgres): PostgreSQL 16.4
* PHP Version: 8.3.9
* Platform / OS: MacOS

### What you did
Updated Migrations Plugin to 4.4.0 which enables the new built-in backend by default.
If one previously had migrations which checked the adapter type via
```
$type = $this->getAdapter()->getAdapterType();
```
this variable previously was `pgsql`

now with the new backend this variable will be `postgres`

Not sure if this is intended or if this was missed when creating the new backend to replace phinx.

I personally am in favor of keeping it this way since it aligns with both the CakePHP Driver classname as well as the schema part in a DSN.

**Comment by markstory** [comment]
> I personally am in favor of keeping it this way since it aligns with both the CakePHP Driver classname as well as the schema part in a DSN. 

I want the backend switch to be as low friction as possible, even if it means preserving bugs in the current method. What I suggest is that we deprecate these methods and remove them in an upcoming major. I'd like to reduce the footprint of migrations anyway and use the ORM/Database packages more for platform specific implementations where possible as well.
