### ISSUE TITLE
Improving foreign key API

### ISSUE THREAD

**Issue by markstory** [cakephp/migrations#770]
Building foreign keys through the `addForeignKey` method requires remembering 4 positional arguments, and the ordering. While it is decent to use when writing migrations it is more reads with more difficulty.

```php
        $this->table('constraint_users')
            ->addForeignKey(
                'role_id',
                'constraint_roles',
                'id',
                [
                    'update' => 'NO_ACTION',
                    'delete' => 'NO_ACTION',
                    'constraint' => 'role_id_0_fk'
                ]
            )
            ->update();
```

Is the current API. We've used up a really good method name with `addForeignKey` and the alternative names I could come up with clunky. What we could do with relative ease though is widen the type on the first parameter of `addForeignKey` to include a new builder object:

```php
        $this->table('constraint_users')
            ->addForeignKey(
                $this->foreignKey('role_id')
                    ->references('constraint_roles', 'id')
                    // Could also be an enum
                    ->updateAction('NO_ACTION')
                    ->deleteAction('NO_ACTION')
                    ->name('role_id_0_fk')
            )
            ->update();
```

While this is more verbose, it is more clear about what is going on, and the API can be well-typed.

**Comment by dereuromark** [comment]
How do we handle (unique) indexes?
Similar?

**Comment by markstory** [comment]
> How do we handle (unique) indexes? Similar?

Yeah I could see a fluent builder object for indexes as well. I'd love to add support for conditional indexes in the future and having a builder would help with that.

**Comment by dereuromark** [comment]
Also refs https://github.com/cakephp/phinx/pull/2322

**Comment by markstory** [comment]
There is already a `Migrations\Db\Table\ForeignKey` class that fills a similar role. Instead of adding new classes and methods, I'll adapt and improve the existing class.

**Comment by dereuromark** [comment]
PR merged.
