### ISSUE TITLE
Configurable migrations

### ISSUE THREAD

**Issue by burzum** [cakephp/migrations#78]
When using plugins there is sometimes the problem that you want to use UUIDs but the plugin has integer type ids and vice versa.

By looking at the migrations they extend the AbstractMigration class, we could add a CakeMigration class from which all migrations extend instead from AbstractMigration directly. That implements an initialize() method where settings from Configure could be read and used for something and other things could be done as well there.

**Comment by dereuromark** [comment]
Sounds like a good idea regarding those keys.

**Comment by HavokInspiration** [comment]
The ``AbstractMigration`` class already has a ``init()`` method that is called on instanciation.
[Ref in phinx source](https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Migration/AbstractMigration.php#L63-L81)
Is that what you are looking for ?

**Comment by burzum** [comment]
@HavokInspiration yes, that could work.
