### ISSUE TITLE
Errors when trying to run (plugin) migration

### ISSUE THREAD

**Issue by burzum** [cakephp/migrations#9]
Please see this screenshot:

https://www.dropbox.com/s/7dop4q5dbur2eo0/Screenshot%202014-10-15%2021.49.13.png?dl=0

First I  run the migrations and the DB table it uses for the schema doesn't exist. It shows a SQL error but the table is created any way. **Edit:** This has been fixed by https://github.com/burzum/migrations-1/commit/ba462266496374a9b42ff7789ce61e4669c181fe

The PR fixes the first issue but I'm still getting this:

```
←[37;41m                                                                           ←[39;49m
←[37;41m  [PDOException]                                                           ←[39;49m
←[37;41m  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id'  ←[39;49m
←[37;41m                                                                           ←[39;49m
```

The table doesn't exist yet, nor does the column.

Here is my migration file:

```php
<?php
use Phinx\Migration\AbstractMigration;

class InitialMigration extends AbstractMigration {

/**
 * Migrate Up.
 */
	public function up() {
		$this->table('statuses')
			->addColumn('id', 'char', ['limit' => 36])
			->addColumn('name', 'char', ['limit' => 255])
			->addColumn('model', 'string', ['limit' => 128])
			->create();
	}

/**
 * Migrate Down.
 */
	public function down() {
		$this->dropTable('statuses');
	}
}
```

**Comment by HavokInspiration** [comment]
A solution to deal with this is proposed in #116
