### ISSUE TITLE
Latest release tags are missing bug fix for migration_snapshot

### ISSUE THREAD

**Issue by kevinquinnyo** [cakephp/migrations#90]
PR #89 fixes a bug that was causing `migration_snapshot` option to not work when invoked from `bake` when you also supplied `--connection` and `--plugin`.

Anyway, if you use the newest release tag for migrations, that bug fix isn't backported, so `migration_snapshot` fails when using the `--connection` and `--plugin` options.

If you use `master` the bug is fixed, but it generates a boilerplate migration snapshot file without any data (I assume because master needs some of the improvements in the release tag commits?).

Can the release tags be updated to include that bug fix?

**Comment by markstory** [comment]
I can tag a release tonight.

**Comment by kevinquinnyo** [comment]
@markstory You rock!

**Comment by markstory** [comment]
1.1.1 released now.

**Comment by kevinquinnyo** [comment]
:+1:  Boom!  Thanks again @markstory You cakephp folks are awesome.
